?{1}{1}23.976
{337}{432}.:: Napisy24.pl - Wprost od t³umaczy ::.
{433}{502}Gdy wróci³eœ,|powiedzia³eœ, ¿e mnie kochasz.
{503}{538}Nie ma nas.
{554}{638}<i>Prowadzê œledztwo w sprawie|zatoniêcia statku </i>Cornwallis<i>.</i>
{640}{738}<i>Chcê pisemnego zeznania,|¿e sir Stuart Strange</i>
{739}{823}zorganizowa³ za³adunek|niewolników na <i>Cornwallis</i>.
{846}{873}Do sejfu.
{927}{1044}Widzia³yœcie transport prochu|i s³ysza³yœcie, dok¹d ma pojechaæ?
{1044}{1128}Na bezpoœrednie polecenie|samego Jamesa Delaneya.
{1131}{1216}Mamy Delaneya, Nootkê|i handel z Chinami.
{1253}{1374}<i>Poprowadz¹ pana po linie|pomiêdzy ¿yciem i œmierci¹.</i>
{1375}{1445}Powiem panu wszystko,
{1445}{1524}w zamian chcê jednego spotkania|ze Stuartem Strange'em.
{1526}{1578}Jeœli to Delaney jest œwiadkiem,
{1579}{1677}<i>to jest przetrzymywany w Tower|z oskar¿eniem o zdradê.</i>
{1678}{1729}Nie, mam innego œwiadka.
{1730}{1786}Przyœlê po ciebie,|gdy bêdziemy gotowi.
{1787}{1823}Nie masz statku!
{1827}{1904}<i>Rozmawia³am ze œwiadkiem.|James nie zabi³ dziewczyny.</i>
{1904}{1940}Zrobi³a to Kompania.
{1940}{1998}– Muszê mu to powiedzieæ.|– Maj¹ go.
{1998}{2053}<i>– Gdzie jest?|– Zabrali go do Tower.</i>
{2066}{2138}– Przyszed³em.|– Mam dla ciebie zadanie.
{3565}{3703}Taboo [S01E08]
{3753}{3779}„<i>Drogi Jamesie,</i>
{3807}{3920}<i>znalaz³am wreszcie drogê ucieczki|z klatki, w której dot¹d ¿y³am.</i>
{3947}{4038}<i>Oczy, o których istnieniu|nie wiedzia³am, zosta³y otwarte.</i>
{4038}{4160}<i>Ujrza³am ograniczenia mego ¿ycia,|¿elazne prêty klatki mej duszy.</i>
{4188}{4286}<i>Nareszcie znalaz³am sposób,|by siê przez nie przecisn¹æ.</i>
{4314}{4420}<i>Mam zamiar porzuciæ spo³eczeñstwo,|Londyn i ca³¹ Angliê.</i>
{4432}{4516}<i>Udaæ siê tam,|gdzie wreszcie bêdê wolna.</i>
{4539}{4651}<i>Do miejsca, gdzie kiedyœ|spotkamy siê i bêdziemy szczêœliwi.”</i>
{5150}{5280}<i>Wtedy zawsze wybiera³em ch³opców|z cieniem œmierci na twarzy.</i>
{5291}{5354}<i>Myœla³em, ¿e rzadziej powróc¹.</i>
{5374}{5503}Oczywiœcie wracaj¹ do mnie...|w postaci duchów.
{5536}{5625}– Teraz, gdy jestem starszy...|– Ilu ch³opców?
{5657}{5776}Ilu ch³opców z Kompanii|wys³a³eœ na swoje prywatne statki?
{5808}{5913}Proszê, nie wierz w to,|¿e jakkolwiek potwierdzê
{5914}{6008}jakiekolwiek dzia³anie -|przesz³e, przysz³e czy teraŸniejsze
{6009}{6107}maj¹ce z tym jakiœ zwi¹zek.
{6275}{6418}Widzisz, ca³y problem w tym,|¿e ty nie zgin¹³eœ.
{6450}{6542}Nawet tam, gdzie gin¹ wszyscy.
{6659}{6768}Nie, nie zgin¹³em.
{6837}{6891}¯ycie zawdziêczam Afrykañczykowi,
{6945}{7046}który mnie ocali³ i uleczy³.
{7096}{7148}Przywróci³ mi ¿ycie.
{7277}{7390}Przy tym, co zrobi³em w Afryce,|twoje transakcje brzmi¹ b³aho.
{7482}{7618}Widzia³em i bra³em udzia³|w ciemnoœci, jakiej nie pojmiesz.
{7703}{7811}W³¹czysz to w swoje zeznania|przed Królewsk¹ Komisj¹?
{7811}{7836}Nie.
{7869}{7931}Nie za to mnie dziœ s¹dz¹.
{8303}{8411}– Zdrajcy dostaj¹ dobre wino.|– Mo¿e dadz¹ ci to samo.
{8618}{8767}Rozumiem, ¿e namówi³eœ Godfreya,|by spisa³ swoje zeznania.
{8968}{9045}Przypuszczam, ¿e chcesz|zawrzeæ jakiœ uk³ad.
{9570}{9619}Tylko na tyle ciê staæ?
{9738}{9869}W zamian za moje milczenie|i spalenie zeznañ Godfreya.
{9932}{10068}– Nie mogê ci tego daæ.|– Lepiej przyzwyczaj siê do smaku.
{10234}{10288}Pracujê nad tym.
{10297}{10426}„Kiedy<i> Cornwallis</i> opuœci³ Kabindê|i sta³ siê<i> Influence</i>,
{10436}{10619}to ja, James Delaney,|schowa³em flagi Anglii i Kompanii.
{10687}{10905}Przemianowany statek Kompanii,|za³adowany niewolnikami,
{10916}{10983}p³yn¹cy pod amerykañsk¹ bander¹
{11097}{11188}na rozkaz sir Stuarta Strange'a”.
{11245}{11277}To zdrada.
{11421}{11464}Jeden ¿yj¹cy œwiadek.
{11465}{11544}Za godzinê przes³uchaj¹ mnie|osobisty sekretarz króla,
{11544}{11683}trzej adwokaci i kilku urzêdników.|Bêd¹ chcieli mieæ to na piœmie.
{11746}{11899}A w samo po³udnie Godfrey,|biedny, uroczy Godfrey
{11936}{12005}z³o¿y swoje zeznanie|przed Królewsk¹ Komisj¹,
{12005}{12201}w którym potwierdzi, ¿e ukry³eœ,|¿e statek i ³adunek nale¿¹ do ciebie.
{12282}{12318}Pope³niaj¹c zdradê.
{12411}{12551}Zatem jest to jeden ¿yj¹cy œwiadek|i zeznanie urzêdnika Kompanii,
{12554}{12670}ujawni informacje,|us³yszane przy podniesionej rêce.
{12959}{13054}Zatrzymaj to.|Ja znam wszystko na pamiêæ.
{13193}{13342}Ja potrzebujê statku,|a ty masz cztery godziny.
{13570}{13683}Brace, wychodzê.|Muszê siê z kimœ spotkaæ.
{14029}{14059}Od pana Delaneya.
{14446}{14602}<i>Panie Cholmondeley!</i>
{14721}{14815}Mam dla pana wiadomoœæ|od pana Delaneya.
{14893}{14936}Jak mnie tu znalaz³eœ?
{14942}{15025}Rozbaw mnie.|Jestem naukowcem, ciekawi mnie to.
{15051}{15171}Widzi mnie w moich snach.|O to chodzi?
{15239}{15277}Jestem tylko pos³añcem.
{15640}{15665}Atticus!
{15731}{15756}Dobry ch³opak.
{15829}{15894}Wilton, Pettifer!
{16017}{16049}Pieprzyæ to!
{16312}{16410}Musicie coœ dla mnie zrobiæ.
{16523}{16611}– Nauczysz mnie?|– Tak, teraz uderz w pi³kê.
{16702}{16789}<i>Zamachnij siê.|Za lekko trzymasz.</i>
{16920}{16947}Gdzie jest druga?
{16950}{17027}– Proszê wybaczyæ.|– Nie mówi, jest w ¿a³obie.
{17028}{17054}Braæ j¹.
{17092}{17190}Powóz ju¿ na nas czeka.|Pojad¹ panie zwiedziæ okolice.
{17223}{17280}Pod przymusem, jeœli trzeba.
{17295}{17324}PrzyprowadŸcie j¹.
{17388}{17489}– Gdzie nas zabieracie?|– Wsiadaj.
{17636}{17666}Jazda.
{18704}{18786}Powiedz im,|¿e nie jestem jeszcze gotowy.
{18803}{18851}Potrzebujê lekarza.
{19208}{19238}Pilnuj go.
{19401}{19539}– Pan Delaney potrzebuje lekarza.|– Z pewnoœci¹ udaje.
{19579}{19648}Czy¿by ju¿ umiera³?
{19775}{19826}SprowadŸ wiêc lekarza.
{19867}{19980}Mo¿emy siê wszyscy modliæ,|¿e nie wypaliliœmy mu mózgu.
{20308}{20334}Staæ!
{20427}{20515}Wy³aziæ, wszyscy, ju¿!
{20601}{20686}Panowie s¹ tu w³aœciwie po to,|by panie uratowaæ.
{20694}{20721}Atticus?
{20725}{20805}Gdybym to ja decydowa³,|dawno temu ju¿ byœ nie ¿y³a.
{20820}{20932}Delaney kaza³ was nie krzywdziæ.|Masz wiele kutasów do obci¹gania.
{20936}{21014}Umowa jest taka,|¿e wy zabieracie panie powozem,
{21015}{21076}a ja wracam|i mówiê, ¿e zosta³y porwane.
{21112}{21212}Twoje ukochane dziecko|zosta³o zabite dla wiêkszego dobra.
{21286}{21332}Prawda, pani Pettifer?
{21384}{21477}Nasi szefowie zawarli umowê.
{21516}{21543}Owszem.
{21647}{21679}Wsiadaæ.
{21876}{21897}Jazda.
{22265}{22317}Bryg o nazwie <i>Good Hope</i>.
{22328}{22436}Ma p³yn¹æ do Konstantynopolu|i wyruszyæ jutro przy odp³ywie.
{22453}{22499}– Ju¿ za³adowany?|– Nie.
{22587}{22643}Spisz dokumenty,|aby zmieniæ jego kurs.
{22651}{22727}Ma p³yn¹æ do Wapping Wall|z podstawow¹ za³og¹.
{22728}{22802}Niech tam zacumuje.|Na pok³adzie ma byæ prowiant.
{22827}{22967}Tyle, by wystarczy³o dla|piêtnastu osób na dwa miesi¹ce.
{22969}{23006}Jaki jest powód podró¿y?
{23051}{23148}Jaki jest oficjalny powód,|który mam wpisaæ do dziennika?
{23155}{23227}Oficjalny powód... pomyœlmy.
{23245}{23370}<i>Good Hope</i> zabrano do Wapping Wall|na nieprzewidziany przegl¹d kad³uba
{23371}{23414}z powodu ma³ej iloœci smo³y,
{23415}{23527}w razie nieuczciwej ksiêgowoœci|budowniczych, Mastera i Preece'a.
{23534}{23576}To wpisz do dziennika.
{23604}{23704}A jaki jest oficjalny powód|wys³ania dwóch wozów Kompanii
{23705}{23745}do zak³adu dla ob³¹kanych?
{23802}{23864}Ca³a ta sprawa jest ob³¹kana.
{23888}{23979}Ten dzieñ jest ob³¹kany,|Delaney jest ob³¹kany!
{23998}{24111}Bo ja jestem ob³¹kany.|Po prostu to zrób.
{24143}{24274}– Czekamy na pana Pettifera?|– Nie, nie czekamy.
{24379}{24414}Spierdalaj st¹d.
{25074}{25156}Wy³aŸcie, i to ju¿.|Musimy spaliæ ten powóz.
{25186}{25286}– Chcê wyjaœnieñ.|– Helgo, wejdŸ tutaj, szybciej.
{25467}{25516}Spokojnie, nie bój siê.
{25598}{25624}Co?
{25650}{25692}Temple by³ na przybrze¿u.
{25710}{25806}Widzia³, jak James œpi w b³ocie|i jak Winter k³adzie siê obok.
{25828}{25955}Potem widzia³ mê¿czyznê w ³odzi.|„Porusza³ siê jak duch”.
{26008}{26072}Ten duch zabi³ œpi¹c¹ Winter.
{26100}{26186}Mê¿czyna wróci³ do ³odzi,|a Temple poszed³ wzd³u¿ brzegu.
{26187}{26258}Zobaczy³, jak mê¿czyzna|z kimœ siê spotyka.
{26268}{26382}Siedzia³ on w powozie,|jak ten, z którego wysiad³yœcie.
{26424}{26469}Kompania Wschodnioindyjska.
{26568}{26686}To prawda, ch³opcze?|Wiesz, co czeka k³amców?
{26691}{26733}Przysiêgam, ¿e to prawda.
{26829}{26892}James proponuje ci nowy pocz¹tek.
{27102}{27139}A wiêc, James...
{27352}{27416}Rzeczy, które wybuchaj¹.
{28004}{28072}To.
{28249}{28300}Rzeczy, które powoduj¹ zamêt.
{28641}{28745}<i>– Chc¹ wiedzieæ, ile to potrwa.</i>|– Co najmniej pó³ godziny.
{28915}{29039}<i>Przysiêgam, jednego prawie zabi³am,|zanim krzykn¹³ „doœæ”.</i>
{29046}{29194}– Dlaczego chc¹ byæ bici?|– Dla si³y, ponoæ to jak sikanie.
{29201}{29299}Zbierasz si³ê w brzuchu|i musisz jakoœ daæ jej ujœcie.
{29310}{29406}NajwyraŸniej bycie pobitym|przez hrabinê dobrze dzia³a.
{29422}{29456}Full.
{29462}{29539}Mo¿e zapytamy doktora D¿ina?
{29585}{29658}– Kto to jest?| Hrabino.
{29695}{29795}– Myœla³am, ¿e bêdzie pani sama.|– Jak pani widzi, nie jestem.
{29801}{29889}– Czego pani chce?|– By³yœmy umówione.
{29898}{29958}Jestem dziœ umówiona|tylko z upojeniem.
{29976}{30048}Jak pani pamiêta,|reprezentujê firmê produkuj¹c¹
{30049}{30133}produkty, które odnawiaj¹|i poprawiaj¹ kobiec¹ urodê.
{30156}{30269}A tak¿e pewien produkt,|który woli pani omówiæ prywatnie.
{30282}{30314}Nie przypominam sobie.
{30315}{30390}Mo¿e oprócz leków|na twój biedny, stary ty³ek,
{30393}{30449}pani ma te¿ coœ na twoj¹ pamiêæ.
{30495}{30559}Ma pani kosmetyk,|który zapewni mi admira³a?
{30560}{30652}Mam taki, który pozwoli pani|przyj¹æ ca³¹ flotê
{30654}{30734}bez dyskomfortu,|tak¿e admira³a i kontradmira³a.
{30760}{30893}Moje produkty zawieraj¹ farby,|olejki, ale g³ównie proszek.
{30958}{31059}Dla tych z nas, które maj¹|sekrety, plamki, niedoskona³oœci...
{31080}{31134}wiemy, jak ukryæ te sekrety.
{31158}{31312}Dla tych, które zrobi¹ wszystko,|gdy ich zapas siê wyczerpie.
{31320}{31482}– Nazwa proszku to „Colonnade”.|– Ma pani próbki?
{31488}{31585}Tak, mo¿e poka¿ê osobiœcie,|jak go najlepiej nak³adaæ?
{31587}{31682}Wrócê przed kanapkami.
{31780}{31827}Jak nudno by³o przed Musgrovem.
{31959}{32077}Co ty wyprawiasz?|Przychodzisz tu i gadasz o prochu?
{32082}{32115}Pracujê dla Delaneya.
{32115}{32167}– Jest w Tower.|– Nie na d³ugo.
{32171}{32201}Wyp³ywa dziœ.
{32223}{32327}Potrzebuje glejtu i kodów flag.
{32365}{32469}– W zamian dostanê traktat?|– Nie.
{32482}{32570}Jest taki list, który wyœlemy|do Solomona Coopa,
{32589}{32689}zdradzaj¹cy, ¿e podniecasz|i upijasz na zlecenie Amerykanów.
{32737}{32808}Jeœli nie wrócê,|dorêcz¹ go w po³udnie.
{32846}{33019}James prosi, by przekazaæ Colonnade,|¿e twój statek przecieka.
{33052}{33158}Znalaz³ ju¿ wyciek i naprawi go,|jeœli ty bêdziesz wspó³pracowaæ.
{33185}{33212}James?
{33259}{33361}– Kim dla niego jesteœ?|– Jestem pani¹ Delaney.
{33380}{33519}– Jego ¿on¹?|– Nie, jego matk¹.
{34494}{34600}– Wiadomoœæ do pana.|– Dziêkujê.
{34736}{34787}„Wypuszczono dziwki”.
{34913}{34993}– Jestem gotowy.|– Nie, jeszcze nie skoñczy³em.
{35005}{35032}Jestem gotowy.
{35228}{35377}Skoro œwiadek zosta³ zszyty,|mo¿emy ju¿ zaczynaæ.
{35391}{35474}Proszê potwierdziæ, ¿e jest pan|Jamesem Keziah Delaneyem
{35474}{35551}z Chamber House|przy Wapping Wall w Londynie,
{35581}{35621}oskar¿onym o spisek
{35621}{35788}z cz³onkami Stowarzyszenia Tajnej|Korespondencji przeciwko królowi.
{35814}{35994}Przysi¹g³eœ wydaæ Amerykanów,|którzy z tob¹ spiskowali
{35996}{36135}i dopuœcili siê aktów zdrady|na terenie miasta Londyn.
{36517}{36549}Panie Delaney...
{36631}{36753}Panie Delaney, jeœli nie poda pan|nazwisk konspiratorów,
{36784}{36911}ka¿dy szew na pana ranach,
{36911}{37024}wyci¹gnê w³asnymi paznokciami.
{37172}{37264}Nazwiska albo tortury!
{37352}{37488}Zmia¿d¿ê ci jaja go³ymi rêkami|i ciê nimi nakarmiê.
{37490}{37583}Obieca³eœ daæ mi nazwiska.
{37844}{37870}Czy¿by?
{38028}{38064}Wiêc k³ama³em.
{38305}{38358}Ale jedno ci powiem.
{38400}{38527}<i>Wszystkie oskar¿enia o zdradê|z³o¿one przez cz³onków Kompanii...</i>
{38569}{38656}zostan¹ wycofane przed po³udniem.
{38705}{38736}Œwiadkowie znikn¹.
{38769}{38814}Zeznania sp³on¹.
{38855}{38944}<i>Popyt siê zaspokoi,|dumê siê prze³knie.</i>
{38944}{39085}<i>Gdy minie ranek, wtedy...</i>
{39114}{39161}<i>bêdê znów wolnym cz³owiekiem.</i>
{39226}{39353}– Sk¹d wiesz?|– Kruki mi powiedzia³y.
{39487}{39573}Kurwa!
{39854}{39879}A wiêc...
{39959}{40018}– To ostatni.|– Tak, proszê pana.
{40027}{40084}Sytuacja siê ponoæ zmieni³a.
{40088}{40200}Rzeczywiœcie, Wasza Wysokoœæ.|Musimy zwolniæ Delaneya.
{40841}{40918}A jednak siê uda.
{41187}{41218}Do roboty, Bill.
{41376}{41423}Wynocha st¹d!
{41472}{41493}Ruszaj.
{41498}{41607}Brighton, Martinez, zamkn¹æ ulicê,|spodziewamy siê goœci.
{41627}{41709}Ca³a reszta, s³yszeliœcie,|zmiataæ mi z ulicy, szybko.
{42050}{42168}– Tak?|– Od pana Delaneya.
{43300}{43431}„<i>Planujê podró¿ do nieba.|Zrozumia³am prawdê.</i>
{43432}{43523}<i>Moje cia³o jest klatk¹,|której mogê siê pozbyæ.</i>
{43546}{43610}<i>Tamiza zabierze mnie do Boga.</i>
{43619}{43713}<i>Œmieræ jest jedynie|ma³ym obrotem klucza w zamku.</i>
{43750}{43880}<i>Choæ Bóg mo¿e mnie nie przyj¹æ.|Mo¿e m¹¿ wspomnia³ o mojej zdradzie.</i>
{43895}{44033}<i>Lub moje uczucia do ciebie,|niewybaczalne uczucia do ciebie,</i>
{44033}{44132}<i>sprawi¹, ¿e Tamiza zabierze mnie|w zupe³nie inne miejsce.</i>
{44135}{44237}<i>Bez wzglêdu gdzie trafiê,|jeœli ty prze¿yjesz swoj¹ brawurê,</i>
{44238}{44355}<i>proszê, zachowaj w swoim sercu|choæ czêœæ mojej duszy”.</i>
{44714}{44847}James, mam glejt.|O ma³o mnie nie zabili.
{44907}{44973}Co robisz?|Musimy wychodziæ.
{45570}{45616}Wiedzia³bym, gdyby umar³a.
{45736}{45835}Us³ysza³bym j¹ i wyczu³...
{45888}{45966}Jakby drzwi siê otworzy³y.
{46045}{46079}Nie.
{46176}{46227}Gdyby by³a w rzece...
{46298}{46330}wo³a³aby do mnie.
{46418}{46522}– A ja bym j¹ us³ysza³.|– Napisa³a z przekonaniem.
{46554}{46652}– To czemu nie wiem?|– Bo zmarli nie wo³aj¹.
{46965}{47075}Skoro nie wo³aj¹,|to dlaczego ich s³yszê?
{47294}{47407}OdpowiedŸ znajdziesz w Ameryce.
{47482}{47507}Czy¿ nie?
{47768}{47799}Mamy przyp³yw.
{47850}{47988}Czeka na ciebie mnóstwo osób,|które dla ciebie porzuci³y wszystko.
{48114}{48205}Zaraz zacznie siê odp³yw.|Woda jej nie zwróci.
{48239}{48339}Mo¿emy tak sobie siedzieæ|w tym gównianym domu
{48364}{48427}i umrzeæ jak twój ojciec.
{48727}{48786}Powinniœmy ruszyæ do Nootki.
{48887}{49027}Jeœli ju¿, to dobry dzieñ,|by umrzeæ na morzu.
{49538}{49615}Mam niedokoñczon¹ sprawê.|Wkrótce wrócê.
{49670}{49708}Razem wejdziemy na statek.
{50316}{50424}Prosto na statek.
{50444}{50481}Przepraszam pana.
{50596}{50657}<i>– Nie mo¿e pan...|– Przepuœæ mnie.</i>
{50657}{50794}Wpuœæ go, niech wejdzie.|Jak postêpuje pana dochodzenie?
{50794}{50928}– To nie przejdzie.|– Wrêcz przeciwnie.
{50933}{50999}Delaney nie u³o¿y siê z tob¹.
{51018}{51115}Zeznanie potwierdzi, ¿e Kompania|wspó³pracowa³a z komisj¹
{51115}{51226}w sprawie zatoniêcia <i>Influence.</i>
{51327}{51435}Jest pan idealist¹.|Delaney i ja jesteœmy realistami.
{51441}{51525}Ró¿nica miêdzy Delaneyem i mn¹
{51534}{51644}jest taka, ¿e zawsze zostawiam|jeszcze jednego asa w rêkawie.
{51769}{51821}Mi³ego dnia.
{51872}{51986}Obiecujê, ¿e to nie przejdzie.
{52383}{52471}Chyba potrzebujesz laudanum.
{52577}{52669}Mam tylko godzinê.|Muszê wyruszyæ przed odp³ywem.
{52691}{52718}Masz statek?
{52797}{52895}Doda³em do laudanum ³opianu,|¿ebyœ móg³ normalnie funkcjonowaæ.
{52905}{52998}W¹tpiê jednak, czy dasz radê|sterowaæ statkiem do Ameryki.
{53000}{53042}Masz ludzi?
{53259}{53399}Zapewne oczekuje pan,|¿e otrzyma pan ode mnie glejt.
{53428}{53510}Obawiam siê jednak,|¿e to nie bêdzie takie proste.
{53515}{53591}Nic nie jest proste|w wojnie pomiêdzy kuzynami.
{53592}{53698}Musi pan wpierw coœ zrobiæ.
{53839}{53872}Proszê spojrzeæ.
{53989}{54051}To akt przeniesienia w³asnoœci.
{54112}{54218}Przenosz¹cy moje prawa do Nootki|na Kompaniê Wschodnioindyjsk¹?
{54285}{54367}I pana kumpla, Stuarta Strange'a.
{54504}{54602}Gdy spotkaliœmy siê pierwszy raz,|powiedzia³ mi pan,
{54610}{54738}¿e owca mo¿e byæ miêsem,|ale mo¿e te¿ byæ we³n¹.
{54782}{54816}Wpierw mi to umknê³o.
{54816}{54947}Potem zrozumia³em, ¿e to nie kod.|Jesteœ ch³opcem na posy³ki.
{54981}{55091}Próbujesz udawaæ poœrednika|wolnych stanów Ameryki,
{55091}{55136}jak dobra owieczka.
{55205}{55316}Ale jesteœ jedynie wabikiem,|którym przed nosem króla Anglii
{55328}{55368}majta Kompania.
{55425}{55651}Teraz desperacko walczysz.|Wciskasz wszystkim w oczy we³nê.
{55712}{55755}Sobie pewnie te¿.
{55964}{56013}Ma to jakieœ znaczenie?
{56199}{56226}Nie.
{56445}{56539}Nikt w tym mieœcie|nie ma tylko jednego pana.
{56615}{56638}Pióro.
{56854}{56884}Ja mam.
{58268}{58443}<i>„James, wróci³eœ.|Powiedzia³eœ, ¿e mnie kochasz.</i>
{58478}{58510}<i>Siostro.</i>
{58591}{58708}<i>James, znów siê zobaczymy.”</i>
{59867}{59945}– Tak, proszê pana?|– W obie rêce.
{60211}{60293}Wzi¹³ chocia¿ kogoœ,|kto wie, jak siê tym p³ywa?
{60375}{60483}¯adnych iskier czy p³omieni,|¿adnych zapalnych komentarzy.
{60490}{60553}Jestem ca³y wybuchowy.
{60826}{60869}<i>Dalej, ³adowaæ.</i>
{60971}{61041}– Gdzie jest Delaney?|– Zajêty.
{61076}{61162}Jest pod bander¹ Kompanii,|wiêc nikt wam nie przeszkodzi.
{61200}{61294}Przeka¿ panu Delaneyowi,|¿e mo¿e wygra³ ma³¹ bitwê,
{61307}{61387}ale sprawiedliwoœæ|i tak zeœle na niego Bóg.
{61403}{61474}Uk³ony od Stuarta Strange'a.
{61578}{61666}Wrzuæcie cia³o do rzeki,|a proch za³adujcie na statek.
{61667}{61760}– Ruchy!|– Do roboty, ruszyæ ty³ki.
{61866}{61974}– Jak siê miewa twoja religia?|– Co moje?
{61974}{62011}Religia, wiara.
{62019}{62120}Po latach w twojej s³u¿bie|jest w strzêpach, Wasza Wysokoœæ.
{62126}{62250}– A rozmawia³eœ o tym z Bogiem?|– Omawiam ró¿ne rzeczy...
{62285}{62350}z ¿on¹, w ³ó¿ku.
{62398}{62477}Ja rozmawiam z Bogiem.|W³aœnie odby³em rozmowê.
{62487}{62547}I co powiedzia³ Bóg?
{62557}{62678}Dyskusje monarchów z Bogiem s¹ tajne|ale powiem ci, o co chodzi.
{62698}{62831}Przez ten gigantyczny bajzel|wszystkich nale¿y powiesiæ.
{62856}{62959}Wschodnioindyjsk¹, Amerykanów,|Irlandczyków, Francuzów,
{62960}{63026}psy, koty, króliki.
{63027}{63157}Wasza Wysokoœæ, nie ma w¹tpliwoœci,|¿e zarz¹d Wschodnioindyjskiej
{63157}{63240}– dogada³ siê z Delaneyem.|– Po prostu go, kurwa, zabij!
{63240}{63325}Jeœli umrze, zgodnie z jego wol¹,|Nootkê dostan¹ Amerykanie.
{63326}{63433}Pierdoliæ Nootkê!|Pierdoliæ testament i umowy.
{63443}{63494}Jestem, kurwa, g³ow¹ pañstwa!
{63529}{63585}I z rozkazu Jego Wysokoœci
{63629}{63656}macie go zabiæ.
{63807}{63845}Mary, z drogi!
{63929}{63981}Gdzie trzymasz wszystkich?
{64048}{64137}– Tam.|– Dobrze.
{64366}{64397}W porz¹dku?
{64413}{64461}15 minut do szczytu przyp³ywu.
{64880}{64991}– £adunki?|– Tak, chemik, to wariat.
{64995}{65063}Cole go chujem za³atwi,|jeœli go nie zastrzel¹.
{65063}{65091}– Ma ¿yæ.|– Czemu?
{65094}{65234}Potrzebujemy go, jest lekarzem.|Proch jest ju¿ na statku?
{65249}{65349}55 beczek jest na pok³adzie,|15 w doku i dwie w wodzie.
{65350}{65471}Jak bêdzie 60 i 10,|wprowadzisz ludzi na statek,
{65471}{65500}przed odp³ywem.
{65514}{65603}– Dok¹d idziesz?|– Przekazaæ plan.
{65603}{65690}Nie chcê, by wiedzieli o planach.|Zreszt¹, ty nie p³yniesz.
{65724}{65750}Co?
{65770}{65863}By³eœ cz³owiekiem mojego ojca|w œwiecie mojego ojca.
{65877}{65919}P³yniemy do mojej matki.
{65956}{66124}Powiedz, ¿e to te¿ z litoœci.|Jestem stary, nie prze¿y³bym.
{66187}{66227}Powiedz, ¿e dlatego.
{66335}{66493}Nie urodzi³eœ siê dla wolnoœci.|Nie poradzi³byœ sobie.
{66536}{66636}To by ciê tylko mêczy³o.|Wracaj do domu.
{66659}{66704}Wszystko teraz jest twoje.
{66782}{66815}¯o³nierze tu s¹.
{66819}{66891}– Atticus, Bill.|– Robert, leæ tam.
{66891}{67014}Niech siê poœpiesz¹ z ³adunkiem.|Ruszaæ siê, szybciej.
{67079}{67128}Id¹ ¿o³nierze, œpieszcie siê.
{67128}{67174}<i>Szybko, ruszaæ siê!</i>
{69634}{69672}<i>Przegrupowaæ siê!</i>
{70325}{70401}– Zaraz odp³yw.|– Dajcie ich na statek, biegiem.
{70560}{70594}Jeszcze nie.
{70906}{70963}Wszyscy wychodziæ.
{71561}{71598}Biegiem!
{71616}{71645}Wsiadaæ.
{71685}{71732}– Zaczekaj.|– Zostaw.
{71782}{71807}Helga!
{71813}{71861}Wchodziæ.
{73267}{73321}Bill!
{73572}{73629}Kurwa!
{74422}{74450}Bill!
{75735}{75824}RAPORT WOJSKOWY
{76030}{76058}Kurwa.
{76152}{76179}Sir.
{76278}{76349}Mój ostatni as.
{76388}{76507}– Wci¹¿ nic od Wiltona i Pettifera.|– Mo¿e wyjechali na weekend.
{76530}{76636}Ja te¿ siê chyba wybiorê.|Sk¹d to siê tu wziê³o?
{76637}{76725}Jakiœ dzieciak to przyniós³,|od niejakiego doktora Dumbartona.
{76725}{76815}– Mówi³, ¿e pan na to czeka.|– Herbata, jak s¹dzê.
{76847}{76903}– Herbata?|– Tak.
{76907}{77044}Ca³a chiñska herbata|i pasek l¹du w dupie œwini.
{77138}{77224}I w koñcu koniec k³opotów.
{77675}{77703}Halo?
{78133}{78191}Przepraszam, by³o otwarte.
{78260}{78295}W³aœnie dosta³em list.
{78444}{78540}Pan Delaney zostawi³ opis|zatoniêcia statku <i>Cornwallis</i>
{78557}{78643}i zeznanie urzêdnika Kompanii.
{78710}{78755}Ma byæ w jego pokoju.
{78832}{78972}– Który jest jego pokój?|– Na poddaszu.
{79049}{79097}Z widokiem na rzekê.
{80761}{80787}Sprawiedliwoœæ.
{82604}{82632}Maria?
{82713}{82845}– Tak.|– Masz takie piêkne palce.
{82870}{82941}– Maria?|– Tak?
{83004}{83061}Wybacz to, co ci zrobi³em.
{83129}{83209}– Przepraszam.|– Wybaczam ci.
{83757}{83793}Dobra stara ³ajba.
{83858}{83971}– A wiêc Ameryka?|– Nie.
{83997}{84048}Ponta Delgada na Azorach.
{84086}{84175}Muszê siê spotkaæ z cz³owiekiem|o nazwisku Collonade.
{84185}{84270}Myœla³em, ¿e wieziemy proch|dla Amerykanów.
{84276}{84322}My jesteœmy Amerykanami.
{84322}{84322}T³umaczenie|Dakota, melyana
{84346}{84441}.:: Napisy24.pl - Wprost od t³umaczy ::.
