<?php

return [

    'tesseract' => [

        // these languages have a .traineddata file
        'languages' => [
            'auto_detect',
//            'afr',
//            'amh',
            'ara',
//            'asm',
//            'aze',
//            'bel',
//            'ben',
//            'bod',
//            'bos',
//            'bul',
//            'cat',
//            'ceb',
//            'ces',
            'chinese', // chi_sim + chi_tra
//            'chr',
//            'cym',
//            'dan',
            'deu',
//            'dzo',
//            'ell',
            'eng',
//            'enm',
//            'epo',
//            'equ',
//            'est',
//            'eus',
            'fas',
            'fin',
            'fra',
//            'frk',
//            'frm',
//            'gle',
//            'glg',
//            'grc',
//            'guj',
//            'hat',
//            'heb',
            'hin',
//            'hrv',
//            'hun',
//            'iku',
//            'ind',
//            'isl',
//            'ita',
//            'jav',
            'jpn',
//            'kan',
//            'kat',
//            'kaz',
//            'khm',
//            'kir',
//            'kor',
//            'kur',
//            'lao',
//            'lat',
//            'lav',
//            'lit',
//            'mal',
//            'mar',
//            'mkd',
//            'mlt',
//            'msa',
//            'mya',
//            'nep',
            'nld',
            'nor',
//            'ori',
//            'osd',
//            'pan',
//            'pol',
//            'por',
//            'pus',
//            'ron',
            'rus',
//            'san',
//            'sin',
//            'slk',
//            'slv',
//            'spa',
//            'sqi',
//            'srp',
//            'swa',
            'swe',
//            'syr',
//            'tam',
//            'tel',
//            'tgk',
//            'tgl',
            'tha',
//            'tir',
//            'tur',
//            'uig',
//            'ukr',
//            'urd',
//            'uzb',
//            'vie',
//            'yid',
        ],
    ],

];


