{1}{1}23.976
{687}{782}www.NapiProjekt.pl - nowa jakoœæ napisów.|Napisy zosta³y specjalnie dopasowane do Twojej wersji filmu.
{783}{903}{Y:i}Django,|czy zawsze by³eœ sam?
{955}{1071}{Y:i}Django,|czy nigdy wiêcej nie kocha³eœ?
{1075}{1155}{y:i}Mi³oœæ bêdzie trwaæ,
{1164}{1237}{y:i}¿ycie iœæ musi naprzód.
{1252}{1374}{y:i}Nie mo¿esz ¿ycia spêdziæ w smutku.
{1440}{1489}DJANGO
{1503}{1612}{Y:i}Django,|musisz zmierzyæ siê z kolejnym dniem.
{1661}{1772}{Y:i}Django,|twoja mi³oœæ teraz odesz³a.
{1789}{1870}{y:i}Niegdyœ j¹ kocha³eœ,
{1875}{1949}{y:i}teraz j¹ straci³eœ.
{1971}{2074}{y:i}Odesz³a bezpowrotnie, Django.
{2180}{2251}{y:i}Gdy niebo zasnute szarymi chmurami
{2252}{2324}{y:i}mo¿esz czuæ smutek,
{2350}{2458}{y:i}lecz pamiêtaj, ¿e mi³oœæ przeminie.
{2509}{2573}{y:i}Och, Django!
{2580}{2652}{y:i}Po deszczu s³oñce jest
{2693}{2773}{y:i}i œwieciæ bêdzie.
{3204}{3285}{y:i}Niegdyœ j¹ kocha³eœ,
{3288}{3362}{y:i}teraz j¹ straci³eœ.
{3396}{3499}{y:i}Odesz³a bezpowrotnie, Django.
{3597}{3665}{y:i}Gdy niebo zasnute szarymi chmurami
{3666}{3738}{y:i}mo¿esz czuæ smutek,
{3772}{3880}{y:i}lecz pamiêtaj, ¿e mi³oœæ przeminie.
{3923}{3987}{y:i}Och, Django!
{3995}{4079}{y:i}Po deszczu s³oñce jest
{4104}{4185}{y:i}i œwieciæ bêdzie.
{4283}{4334}{y:i}Django!
{4353}{4428}{y:i}Och Django!
{4434}{4502}{y:i}Musisz dalej iœæ.
{4506}{4579}{y:i}Och, Django!
{4655}{4755}T³umaczenie: hellcat|Korekta: Gall Anonim, maz445
{5289}{5371}Dwa lata przed Wojn¹ Secesyjn¹
{5415}{5489}gdzieœ w Teksasie
{6214}{6284}Kogo tam niesie po nocy?
{6292}{6374}Mów, w czym sprawa,|albo ciê zdmuchniemy!
{6386}{6492}Spokojnie, panowie.|Nie obawiajcie siê mnie.
{6505}{6611}Jestem tylko znu¿onym wêdrowcem.
{6656}{6707}Ch³odny wieczór, panowie.
{6708}{6802}Szukam pary handlarzy niewolników,|których zw¹ Bracia Speck.
{6803}{6865}Czy¿ to wy?
{6882}{7008}- A kto pyta?|- Dr King Schultz. A to mój koñ, Fritz.
{7039}{7124}- Niby jaki doktor?|- Dentysta.
{7125}{7226}Jesteœcie Bracia Speck i kupiliœcie|tych niewolników na aukcji w Greenville?
{7227}{7302}- I co z tego?|- Wiêc chcê z wami pertraktowaæ.
{7303}{7344}Mów¿e po angielsku.
{7345}{7444}Wybaczcie mi.|To mój drugi jêzyk.
{7448}{7520}S¹dzê, ¿e poœród waszego|inwentarza s¹ osobniki,
{7521}{7581}które skory jestem pozyskaæ.
{7582}{7644}Czo³em, czorty!
{7645}{7775}Czy któryœ z was zamieszkiwa³|niegdyœ Plantacjê Carrucan?
{7815}{7893}Ja jestem z Plantacji Carrucan.
{7909}{7971}Który to powiedzia³?
{9070}{9122}Jak siê nazywasz?
{9204}{9254}Django.
{9259}{9339}Wiêc jesteœ tym, którego szukam.
{9362}{9436}Wiesz, kim s¹ Bracia Brittle?
{9510}{9583}Co to za jedni?
{9584}{9683}Du¿y John, Ellis,
{9705}{9807}Roger, zwany te¿ Ma³y Raj.
{9832}{9929}- Byli nadzorcami na Plantacji Carrucan.|- Ju¿ nie.
{9996}{10100}Jeœli znowu zobaczy³byœ|tych trzech d¿entelmenów,
{10101}{10161}rozpozna³byœ ich?
{10170}{10240}- Nie gadaj tak do niego.|- Jak?
{10242}{10341}- W³aœnie tak.|- Dobry cz³owieku. Usi³ujê jedynie ustaliæ...
{10342}{10433}- Mów po ludzku, do cholery.|- Spokojnie.
{10434}{10529}Jestem jedynie klientem|chc¹cym przeprowadziæ transakcjê.
{10530}{10610}Nie na sprzeda¿.|Zmiataj ju¿.
{10611}{10696}Niedorzecznoœæ.|Oczywiœcie, ¿e s¹ na sprzeda¿.
{10697}{10758}- Jazda st¹d.|- Dobry cz³owieku,
{10759}{10831}ponosz¹ pana teatralne gesty,
{10832}{10928}czy celuje pan tê broñ|ze œmiertelnym zamiarem?
{10974}{11046}Ostatnia szansa, gogusiu.
{11051}{11112}Wiêc dobrze.
{11802}{11865}Wybacz, ¿e postrzeli³em twoje zwierzê.
{11866}{11916}Nie chcia³em,|byœ wykona³ pochopny ruch,
{11917}{11967}przed zrozumieniem swojego b³êdu.
{11968}{12042}Szlag by ciê, skurwielu!
{12056}{12106}Zastrzeli³eœ Rustle'a.
{12137}{12164}I zabi³eœ Ace'a.
{12165}{12238}Tylko dlatego, ¿e grozi³,|¿e zabije mnie.
{12239}{12387}I s¹dzê, ¿e znajdê piêciu œwiadków,|którzy to potwierdz¹.
{12388}{12431}Nogê mi przygniot³o!
{12432}{12535}Bez w¹tpienia. Jeœli by³byœ ³askaw|powstrzymaæ to miauczenie,
{12536}{12610}chcia³bym kontynuowaæ rozmowê z Django.
{12723}{12778}Wiêc jak ju¿ mówiliœmy.
{12786}{12872}Czy rozpozna³byœ Braci Brittle?
{12891}{12929}Tak.
{12937}{12970}Sprzedany!
{12971}{13058}Panie Speck!|Ile za m³odego Django?
{13204}{13264}To dopiero paskudny biznes.
{13389}{13461}Przytrzymasz?
{13490}{13563}Django, wskakuj na tamtego konia.
{13583}{13665}Na twoim miejscu|wzi¹³bym równie¿ zimowy p³aszcz,
{13666}{13752}który pozostawi³ nasz drogi|zmar³y Speck.
{14053}{14138}Nie wa¿ siê tkn¹æ p³aszcza|mojego brata.
{14569}{14608}Sto...
{14609}{14705}dziesiêæ... dwadzieœcia i piêæ.
{14762}{14798}Za m³odego Django.
{14799}{14861}I jako, ¿e ju¿ nie bêdzie|jej potrzebowa³,
{14862}{14926}chcia³bym zakupiæ|chabetê pana brata.
{14927}{14991}Ponadto, panie Speck,
{14992}{15040}obawiam siê,|¿e bêdê potrzebowa³ rachunek.
{15041}{15085}Posiada pan?
{15086}{15160}IdŸ w cholerê, dentysto!
{15173}{15245}Zapewne nie.|Bez obaw.
{15258}{15330}Jestem przygotowany.
{15409}{15534}Dziêkujê.|To bêdzie godnie s³u¿yæ za rachunek.
{15954}{16042}A co do was, biedne czorty...
{16052}{16152}Jak widzê, zmierzamy do tematu
{16153}{16192}co pocz¹æ dalej.
{16193}{16245}Macie panowie dwie opcje.
{16247}{16272}Pierwsza.
{16273}{16361}Jak tylko odjadê,|mo¿ecie podnieœæ t¹ ³achudrê Specka
{16362}{16417}i zanieœæ go|do najbli¿szego miasta.
{16418}{16502}Które bêdzie jakieœ 37 mil st¹d.
{16509}{16558}Lub druga.
{16560}{16615}Rozkujecie siê,
{16617}{16717}weŸmiecie strzelby,|odstrzelicie mu ³eb, zakopiecie g³êboko
{16718}{16815}i znajdziecie drogê do bardziej|oœwieconych terenów tego kraju.
{16824}{16873}Wasz wybór.
{16885}{16968}W razie gdyby poœród was|nie by³o mi³oœników astronomii,
{16969}{17041}Gwiazda Pó³nocna, to tamta.
{17510}{17582}Chwileczkê, panowie.|Pogadajmy o tym.
{17693}{17753}B¹dŸcie rozs¹dni.
{17795}{17879}Nie jestem z³ym cz³owiekiem.|Tylko robiê co do mnie nale¿y.
{17880}{17952}Blueberry, czy nie da³em ci|mojego ostatniego jab³ka?
{17953}{17994}S³uchajcie, ch³opaki...
{17995}{18074}zabierzcie mnie do lekarza|w El Paso, to was uwolniê.
{18101}{18150}Nie, proszê...
{19279}{19311}Dobrze wiêc...
{19312}{19396}weŸmie pani dzisiaj 2 pigu³ki,|a rano...
{19469}{19529}Czarnuch wierzchem jedzie.
{20118}{20168}Na co oni tak patrz¹?
{20170}{20256}Nigdy wczeœniej nie widzieli|czarnego na koniu.
{20785}{20846}Dzieñ dobry, gospodarzu!
{20869}{20935}Dwa piwa dla znu¿onych wêdrowców.
{20936}{20977}Wczeœnie jeszcze...
{20978}{21039}Jeszcze przez godzinê|bêdzie zamkniête.
{21040}{21107}Na razie podajemy œniadania.
{21167}{21263}Co to ma znaczyæ?|Zabieraj pan st¹d tego smolucha.
{21435}{21469}Gospodarzu...
{21470}{21556}wezwij szeryfa miejskiego,|nie federalnego.
{21588}{21637}Nareszcie...
{21661}{21758}Teraz bêdziemy musieli|sami siê obs³u¿yæ.
{21782}{21841}Siadaj, ch³opcze.
{22052}{22117}Co za dentyst¹ jesteœ?
{22146}{22255}Nie zajmowa³em siê stomatologi¹|od piêciu lat.
{22363}{22436}Teraz param siê now¹ profesj¹.
{22500}{22548}£owca G³ów.
{22682}{22730}Wiesz, kto to taki?
{22734}{22765}Nie.
{22766}{22802}Wiêc...
{22838}{22935}tak jak w niewolnictwie przedmiotem|interesu s¹ ludzkie ¿ycia,
{22936}{23003}w mojej profesji s¹ to zw³oki.
{23145}{23195}{y:i}Prost!
{23378}{23436}Stan ustala nagrodê za kogoœ.
{23437}{23494}Œcigam tego cz³owieka,|znajdujê go, zabijam,
{23495}{23588}jak ju¿ zabijê, transportujê zw³oki|tego cz³owieka do w³adz,
{23589}{23670}co czasami ³atwiej powiedzieæ,|ni¿ zrobiæ.
{23672}{23777}Okazujê te zw³oki w³adzom,|udowadniaj¹c, ¿e w istocie go zabi³em.
{23778}{23862}I po tym w³adze|wyp³acaj¹ mi nagrodê.
{23888}{23963}Czyli handel miêsem,|tak jak niewolnictwo.
{23985}{24045}Co to jest "nagroda"?
{24102}{24153}Coœ jak zap³ata.
{24154}{24231}Zabijasz ludzi|i p³ac¹ ci za to?
{24233}{24274}Pewnych ludzi.
{24275}{24325}Z³ych ludzi?
{24326}{24400}Im bardziej Ÿli,|tym wiêksza zap³ata.
{24401}{24464}Co sprowadza mnie do ciebie.
{24465}{24560}I jak muszê przyznaæ,|mam co do ciebie rozterki.
{24561}{24633}Z jednej strony gardzê niewolnictwem.
{24634}{24686}A z drugiej...
{24688}{24761}potrzebujê twojej pomocy,|wiêc jeœli nie zamierzasz odmówiæ,
{24762}{24810}to tym lepiej.
{24814}{24913}Dlatego póki co, uczyniê u¿ytek|z tego bzdurnego procederu.
{24930}{25000}Wci¹¿ jednak,|jak ju¿ powiedzia³em,
{25001}{25059}czujê siê winny.
{25134}{25231}Chcia³bym wiêc,|¿ebyœmy zawarli we dwóch umowê.
{25383}{25444}Szukam Braci Brittle.
{25544}{25623}Jednak¿e w tym d¹¿eniu|jestem nieco ograniczony,
{25624}{25710}gdy¿, jak dot¹d, nie wiem,|jak oni wygl¹daj¹.
{25736}{25800}Lecz ty tak, prawda?
{25806}{25858}Wiem, jak wygl¹daj¹.
{25861}{25887}Dobrze.
{25889}{25950}Wiêc umowa jest taka:
{25951}{26001}podró¿ujesz ze mn¹,|a¿ ich znajdziemy.
{26002}{26039}Gdzie jedziemy?
{26040}{26099}Wiem, ¿e przynajmniej dwóch z nich|nadzoruje w Gatlinburgu,
{26100}{26148}ale nie wiem gdzie.
{26155}{26253}Odwiedzimy wiêc tam ka¿d¹ plantacjê,|a¿ ich znajdziemy.
{26266}{26344}A jak ich znajdziemy,|ty ich wska¿esz,
{26345}{26405}a ja ich zabijê.
{26420}{26500}Zrobisz to, a ja ci dam wolnoœæ.
{26501}{26584}25 $ za ka¿dego brata,|co daje 75 $.
{26601}{26683}I tak jak przewidzia³em,|nadchodzi szeryf.
{26875}{26952}Dobra, ch³opaki,|koniec zabawy.
{26978}{27027}Wy³aziæ.
{27092}{27140}Dobra, ludziska.
{27149}{27223}Spokojnie...|Wracajcie do roboty.
{27289}{27349}¯artownisie zaraz znikn¹
{27394}{27498}Dlaczego przyje¿d¿acie do mojego miasteczka|i zaczynacie grandziæ?
{27526}{27600}Straszyæ tych mi³ych ludzi.
{27614}{27739}Nie macie nic lepszego do roboty,|ni¿ przyje¿d¿aæ do miasteczka Billa Sharpa
{27740}{27814}i pokazywaæ swoje dupska?
{28022}{28084}Coœ pan zrobi³ szeryfowi?
{28379}{28441}Teraz mo¿esz iœæ po federalnego.
{28534}{28558}Wejdziesz do œrodka?
{28559}{28608}Nie mo¿emy zwiaæ?
{28687}{28771}WeŸcie te powozy,|ustawcie na linii wzd³u¿ salonu.
{28772}{28852}Chcê za nimi szeœciu|mê¿czyzn ze strzelbami.
{28853}{28907}Dwóch ze strzelbami|na tamtym dachu.
{28908}{28955}Dwóch ze strzelbami|na tamtym.
{28957}{29030}Wszystkie lufy skierowane|na frontowe drzwi.
{29043}{29127}Niech weŸmie któryœ z ulicy|biednego Billa.
{29150}{29200}Wy tam w salonie!
{29201}{29287}Mamy setki strzelb przed ka¿dym|wyjœciem z budynku.
{29289}{29379}Macie tylko jedn¹ szansê,|by wyjœæ z tego ¿ywo.
{29383}{29488}Ty i twój czarnuch,|wychodziæ natychmiast z rêkoma w górze.
{29529}{29621}Czy mam przyjemnoœæ|zwracaæ siê do szeryfa federalnego?
{29622}{29664}Tak, to ja.
{29665}{29719}Szeryf federalny Gill Tatum.
{29732}{29780}Wunderbar!
{29784}{29878}Pozby³em siê ca³ej swojej broni.
{29879}{30025}I zgodnie z pana poleceniem|gotów jestem wyjœæ
{30026}{30108}z rêkoma uniesionymi nad g³ow¹.
{30149}{30282}Ufam, ¿e jako reprezentuj¹cy|wymiar sprawiedliwoœci U.S.A.,
{30283}{30422}nie zostanê postrzelony na ulicy,|przez pana lub pana podw³adnych,
{30423}{30505}dopóki nie doczekam procesu w s¹dzie.
{30517}{30568}Tak jak zastrzeli³eœ naszego szeryfa?
{30569}{30618}Jak psa na ulicy.
{30620}{30665}To w³aœnie mia³em na myœli.
{30666}{30739}Czy zapewnia pan,|jako przedstawiciel prawa,
{30740}{30819}¿e nie odstrzeli mnie,|jak psa na ulicy?
{30896}{30969}Choæ wszyscy lubimy|takie widowiska,
{30970}{31051}nikt w moim mieœcie|kata nie oszuka.
{31071}{31152}Dobrze wiêc, szeryfie,|ju¿ idziemy.
{31192}{31278}Sporo tam na zewn¹trz napiêcia,|wiêc nie rób ¿adnych
{31279}{31352}gwa³townych ruchów|i pozwól mi mówiæ.
{31357}{31406}Wy³aziæ.
{31577}{31602}Jesteœcie nieuzbrojeni?
{31603}{31652}W istocie, jesteœmy.
{31666}{31741}Czy mogê przemówiæ do pana,|pañskich podw³adnych
{31742}{31801}oraz widocznie ca³ego|zgromadzonego miasteczka,
{31802}{31874}w kwestii incydentu,|który siê wydarzy³?
{31881}{31931}Œmia³o.
{31957}{32001}Jestem Dr King Schultz.
{32002}{32076}I tak, jak pan,|jestem w s³u¿bie s¹du.
{32090}{32132}Ten trup le¿¹cy w brudzie,
{32133}{32215}którego mieszkañcy Daughtrey uznali|za pasuj¹cego na swojego szeryfa,
{32217}{32264}znany pod imieniem Bill Sharp,
{32265}{32363}jest poszukiwanym kryminalist¹,|Willardem Peckiem,
{32364}{32442}z nagrod¹ za g³owê w wysokoœci 200 $.
{32443}{32519}Za ¿ywego lub martwego.
{32537}{32564}Co ty u diab³a bredzisz?
{32565}{32650}Jestem œwiadomy,|¿e to zawstydzaj¹ce wieœci.
{32651}{32749}Zak³adam jednak, ¿e szeryf|zosta³ wybrany w przeci¹gu
{32750}{32798}dwóch ostatnich lat.
{32858}{32954}Wiem to, gdy¿ trzy lata temu|krad³ byd³o od B.C. Corrigan
{32955}{33041}Cattle Company w Lubbock w Teksasie.
{33043}{33137}To jest nakaz podpisany|przez sêdziego s¹du okrêgowego
{33138}{33234}Henry'ego Allena Laudermilka|z Austin w Teksasie.
{33261}{33305}Mo¿e pan zatelegrafowaæ.
{33307}{33428}Potwierdzi to, kim jestem ja|i kim odesz³y szeryf by³.
{33634}{33724}Innymi s³owy, wisi mi pan 200 $.
{34650}{34723}Jak ju¿ sprawa braci Brittle|bêdzie za nami,
{34724}{34780}bêdziesz wolnym cz³owiekiem,
{34781}{34854}z koniem i 75-oma dolarami w kieszeni.
{34934}{34989}Co wtedy zamierzasz?
{35026}{35104}ZnaleŸæ ¿onê i wykupiæ jej wolnoœæ.
{35166}{35215}Django...
{35218}{35293}nie mia³em pojêcia,|¿e jesteœ ¿onaty.
{35301}{35384}Czy wiêkszoœæ niewolników|akceptuje ma³¿eñstwo?
{35385}{35438}Ja z ¿on¹ tak.
{35446}{35509}Stary Carrucan nie,
{35510}{35558}no to uciekliœmy.
{35576}{35627}Django...
{35692}{35746}masz charakter, Django.
{35774}{35829}Ch³opak ma charakter.
{35866}{35939}Nic mi po czarnuchu|z charakterem.
{35979}{36060}Wypalicie mu "r" uciekiniera|na policzku.
{36062}{36112}Dziewczynie te¿.
{36145}{36218}WeŸcie ich na aukcjê w Greenville.
{36228}{36276}I sprzedajcie.
{36281}{36329}Oboje.
{36331}{36380}Oddzielnie.
{36435}{36486}A tego tu...
{36523}{36577}sprzedacie tanio.
{36627}{36675}W Greenville...
{36732}{36814}powinno byæ coœ|w rodzaju biura rejestrów.
{36965}{37040}Wiesz, kiedy zosta³a sprzedana.
{37064}{37124}Wiesz, sk¹d pochodzi
{37139}{37193}i znasz jej imiê.
{37196}{37249}Jak mia³a na imiê?
{37252}{37301}Broomhilda.
{37315}{37344}Jak?
{37345}{37394}Broom-hilda.
{37398}{37447}Brunhilda?
{37498}{37543}Jej w³aœciciel by³ Niemcem?
{37544}{37589}Sk¹d wiesz?
{37591}{37689}Wychowa³a j¹ niemiecka guwernantka.|Von Shaft.
{37693}{37747}Mówi te¿ po niemiecku.
{37748}{37792}Twoja ¿ona?
{37794}{37878}Niemka uczy³a j¹,|¿eby mia³a z kim pogadaæ.
{37927}{37964}Chwila, sprecyzujmy to.
{37978}{38050}Twoja ¿ona niewolnica mówi|po niemiecku
{38051}{38123}i nazywa siê Brunhilda|von Shaft?
{38227}{38292}Mówi¹ na mnie Hildie.
{38680}{38757}Gdy ju¿ znajdziemy|siê na plantacji,
{38766}{38838}bêdziemy udawaæ kogoœ innego.
{38855}{38915}Bêdziesz odgrywa³ postaæ.
{39125}{39173}Nie?
{39332}{39429}Podczas udawania nie mo¿esz|nigdy wyjœæ z tej roli.
{39463}{39511}Rozumiesz?
{39519}{39541}Tak.
{39542}{39596}Nie wyjœæ z roli.
{39633}{39710}I twoja postaæ jest lokajem.
{39744}{39793}Co to jest?
{39804}{39864}Fantazyjnie ubrany s³u¿¹cy.
{39865}{39914}Lokaj.
{39919}{40025}A teraz, Django, mo¿esz wybraæ|kostium dla twojej postaci.
{40096}{40142}Mogê sam wybraæ dla siebie ubrania?
{40143}{40192}Oczywiœcie.
{40283}{40340}{y:i}Na imiê mu by³o King.
{40342}{40400}{y:i}Mia³ konia.
{40415}{40471}{y:i}Widzia³am go,
{40473}{40525}{y:i}jak przeje¿d¿a³ nim przez wioskê.
{40533}{40583}{y:i}Mia³ broñ.
{40592}{40646}{y:i}O tak, zna³am go dobrze.
{40654}{40708}{y:i}A kiedy strzela³,
{40709}{40798}{y:i}ten cz³owiek nigdy nie chybia³.
{40822}{40872}{y:i}JedŸ King, dalej,
{40873}{40931}{y:i}dorwij tego czlowieka.
{40991}{41078}Prawo na tym terenie zakazuje|czarnym jeŸdziæ konno.
{41079}{41163}To mój lokaj,|nie bêdzie chodzi³ pieszo.
{41164}{41211}Powiedzia³em, ¿e czarnuchy...
{41212}{41278}On nazywa siê Django,|jest wolnym cz³owiekiem
{41279}{41329}i mo¿e jeŸdziæ czym mu siê podoba.
{41330}{41372}Nie na mojej posiad³oœci.
{41373}{41421}Nie wœród moich czarnych.
{41432}{41476}Drogi panie...
{41479}{41550}byæ mo¿e Ÿle zaczêliœmy.
{41552}{41619}Pozwól mi naprawiæ swój b³¹d.
{41621}{41706}Jestem Dr King Schultz,|to jest mój lokaj Django,
{41707}{41780}a to s¹ nasze konie, Tony i Fritz.
{41853}{41991}Panie Bennett, przekonywano mnie,|¿e d¿entelmenem z pana i biznesmen
{41999}{42114}i przez wzgl¹d na te przymioty,|podró¿owaliœmy z Teksasu do Tennessee,
{42115}{42165}aby z panem pomówiæ.
{42166}{42252}Chcia³bym kupiæ jedn¹|z pañskich czarnulek.
{42305}{42385}Ty i twój przydupas jechaliœcie|z Teksasu do Tennessee,
{42386}{42429}¿eby kupiæ jedn¹ z moich czarnych?
{42430}{42472}Bez umawiania, bez niczego?
{42473}{42525}Obawiam siê, ¿e tak.
{42526}{42585}To co powiesz na to, ¿e ciê nie lubiê,
{42586}{42634}ani twojego fircykowatego lokaja,
{42635}{42689}i nie sprzeda³bym ci|z³amanego grosza?
{42690}{42747}Co powiesz na to?
{42814}{42897}Panie Bennett,|jeœli jest pan biznesmenem,
{42898}{42955}a tak mi powiedziano,
{42956}{43010}mogê podaæ 5000 powodów,
{43011}{43069}mog¹cych zmieniæ pana zdanie.
{43166}{43248}WejdŸcie proszê do œrodka,|napijcie siê czegoœ zimnego.
{43631}{43716}Mo¿e w czasie, gdy bêdziemy omawiaæ|nasz interes, jedno z pana
{43717}{43796}uroczych stworzeñ oprowadzi|Django po pana wspania³ych terenach.
{43797}{43838}Jak najbardziej. Betina!
{43839}{43885}Tak, Tatuœku?
{43886}{43927}Jak on siê nazywa?
{43929}{43979}Django.
{44001}{44106}Betina, mog³abyœ zabraæ Django|i pokazaæ mu nasze wspania³oœci?
{44107}{44160}Jak sobie ¿yczysz, Tatuœku.
{44178}{44245}Panie Bennett, muszê przypomnieæ,|¿e Django jest wolnym cz³owiekiem.
{44246}{44291}Nie mo¿e byæ traktowany|jak niewolnik.
{44292}{44385}W granicach dobrego smaku,|uwa¿ajcie go za reprezentanta mojej osoby.
{44386}{44435}Zrozumiano, Schultz.|Betina, s³oñce?
{44436}{44461}Tak?
{44462}{44511}Django nie jest niewolnikiem.
{44512}{44573}Jest wolnym cz³owiekiem.|Rozumiesz?
{44590}{44710}Nie mo¿esz go traktowaæ jak jakiegoœ|g³upiego czarnucha, bo nim nie jest.
{44747}{44807}Mam go traktowaæ jak bia³ego?
{44808}{44844}Nie.
{44846}{44897}Nie to powiedzia³em.
{44898}{44968}No to nie wiem, o co ci chodzi,|Tatuœku.
{44969}{45018}W³aœnie widzê.
{45082}{45157}Jak siê nazywa ten ch³opak|z miasta, od szk³a?
{45162}{45236}Jego matka robi|w sk³adzie drzewnym.
{45241}{45272}Jerry?
{45273}{45311}W³aœnie, Jerry.
{45312}{45353}Znasz Jerry'ego, s³oñce?
{45354}{45389}Tak, Tatuœku.
{45390}{45429}To o to chodzi...
{45430}{45481}Traktuj go jak Jerry'ego.
{45660}{45734}Dom, co z niego wyszliœmy,|to Du¿y Dom.
{45736}{45808}Tatusiek tak na niego mówi,|bo jest du¿y.
{45833}{45917}Tamto jest spi¿arnia.|Tam Tatusiek wiesza miêso.
{45989}{46039}Biedne ma³e wiewiórki.
{46063}{46124}Co robisz dla swojego pana?
{46133}{46178}Nie s³ysza³aœ,|¿e nie jestem niewolnikiem.
{46179}{46202}Naprawdê jesteœ wolny?
{46203}{46229}Tak.
{46231}{46305}To mówisz,|¿e sam siê tak ubierasz?
{46337}{46381}Betina, muszê ciê spytaæ o coœ.
{46382}{46410}Czego chcesz?
{46412}{46447}Szukam trzech bia³ych.
{46448}{46508}Trzech braci nadzorców,|zw¹ ich Brittle.
{46509}{46526}Znasz ich?
{46527}{46546}Brittle?
{46548}{46631}Tak, Brittle.|John, Ellis i Roger.
{46642}{46685}Mówi¹ te¿ na niego Ma³y Raj.
{46686}{46722}Nie znam ich.
{46726}{46782}Mog¹ u¿ywaæ innych imion.
{46785}{46834}Mogli przyjechaæ na plantacjê|zesz³ego roku.
{46835}{46871}Chodzi ci o Schafferów?
{46873}{46906}Mo¿e tak.
{46907}{46955}Trzech braci?
{46957}{47007}S¹ tutaj?
{47010}{47055}Mo¿esz ich wskazaæ?
{47057}{47107}Jeden jest tam na polu.
{47446}{47517}Carrucanowi siê nie spodoba...|Ona s³u¿y w domu...
{47518}{47554}Skórê jej zniszczycie,
{47555}{47613}funta k³aków nie bêdzie warta...
{47791}{47837}Mówiê ci, to ja j¹ zmusi³em.
{47839}{47864}Gotowa?
{47865}{47947}Pobieg³a za mn¹,|ja tam powinienem byæ!
{47948}{48027}Wiesz to dobrze John, od dawna tu jestem,|znasz mnie przecie¿.
{48268}{48351}Pan Carrucan nie pochwali tego,|ona s³u¿y w domu.
{48966}{49034}Jeœli tego w³aœnie chcesz,|to b³agam ciê na kolanach.
{49201}{49270}Lubiê jak b³agasz, ch³opcze.
{49337}{49387}To tego szukasz?
{49439}{49477}Taa.
{49493}{49530}Gdzie dwaj pozostali?
{49531}{49611}Przy stajni.|Karz¹ Ma³¹ Jody za zbicie jajek.
{49633}{49679}Biczuj¹ ma³¹ Jody?
{49680}{49729}Wska¿ mi kierunek.
{49738}{49817}Pójdziesz do tamtego drzewa|i dalej prosto.
{49933}{50007}IdŸ po bia³ego,|z którym przyszed³em.
{50160}{50222}{y:i}Niechaj siê was boi...
{50244}{50292}{y:i}i lêka...
{50293}{50358}{y:i}wszelkie zwierzê na ziemi.
{50897}{50947}Dobra, jest gotowa!
{51283}{51372}Zobaczymy, czy po tym|znowu st³uczesz jajka.
{51462}{51500}John Brittle!
{51992}{52028}Pamiêtasz mnie?
{52331}{52392}Lubiê jak zdychasz,|ch³opcze.
{52528}{52573}Skurczybyk!
{53650}{53698}Chcecie coœ zobaczyæ?
{54052}{54102}Co to za jedni?
{54118}{54148}To Du¿y John.
{54149}{54180}To Ma³y Raj.
{54181}{54226}Gdzie Ellis?
{54230}{54299}W³aœnie zwiewa przez tamto pole.
{54400}{54434}To na pewno on?
{54436}{54463}Jesteœ przekonany?
{54464}{54513}- Nie wiem.|- Nie jesteœ przekonany?
{54514}{54563}- Nie wiem, co znaczy przekonany.|- To znaczy pewny.
{54564}{54580}Tak.
{54581}{54643}- Co tak?|- Tak, jestem pewny, ¿e to on.
{54954}{55004}Jestem przekonany, ¿e by³.
{55189}{55285}Proszê wszystkich o spokój.|Nikogo wiêcej nie krzywdzimy.
{55291}{55341}Co wy za pajace?
{55351}{55481}Dr King Schultz, legalny reprezentant|wymiaru sprawiedliwoœci U.S.A.,
{55482}{55571}a cz³owiek po lewej, to Django,|mój zastêpca.
{55599}{55669}W kieszeni mam pe³nomocnictwo,|podpisane przez sêdziego
{55670}{55742}s¹du okrêgowego Henry'ego Allena|Laudermilka z Austin w Teksasie,
{55743}{55824}do schwytania, ¿ywych lub martwych,
{55853}{55946}Johna Brittle, Rogera Brittle|i Ellisa Brittle.
{55976}{56049}Znanych pod nazwiskiem Schaffer.
{56059}{56156}Wy ich znacie jako Schaffer,|ale rzeŸnicy nazywali siê Brittle.
{56165}{56201}To poszukiwani ludzie.
{56202}{56244}Prawo œciga ich za morderstwo.
{56245}{56337}Powtarzam: ¿ywych lub martwych.
{56344}{56465}Wykonuj¹c wiêc egzekucjê,|dzia³aliœmy w granicach prawa.
{56535}{56620}Rozumiem, ¿e wzburzenie jest wielkie.
{56653}{56700}Lecz muszê was ostrzec,
{56701}{56783}¿e kar¹ za powziêcie zabójczych zamiarów
{56784}{56831}nad reprezentantem prawa na s³u¿bie,
{56832}{56899}bêdzie powieszenie z efektem œmiertelnym.
{56986}{57033}Mogê wyci¹gn¹æ pe³nomocnictwo z kieszeni,
{57034}{57090}by móg³ je pan sprawdziæ?
{57144}{57187}Dawaj.
{57567}{57617}Usatysfakcjonowany?
{57758}{57807}Mogê dostaæ z powrotem?
{57944}{57985}Wynoœcie siê z mojej ziemi.
{57986}{58031}Niezw³ocznie.
{58040}{58094}Za³aduj cia³a jak najszybciej.
{58096}{58141}I wynoœmy siê st¹d.
{58794}{58843}To te skurwysyny.
{60194}{60287}Dopóki sami nie zaczn¹ strzelaæ,|nie otwierajcie ognia.
{60307}{60375}To by by³o dla nich zbyt ³askawe.
{60380}{60443}Wysmagamy mi³oœnika|czarnuchów na œmieræ.
{60444}{60514}A ja osobiœcie pasy zedrê|z tego ma³piszona.
{60702}{60771}Ni cholery przez to kurewstwo nie widzê.
{60795}{60834}Zaczynamy, czy jak?
{60835}{60896}Zara, tylko te dziury poszerzê.
{60966}{61009}Zjeba³em jeszcze bardziej.
{61010}{61056}Kto robi³ to badziewie?
{61057}{61087}¯ona Willarda.
{61089}{61140}Sam sobie zrób maskê!
{61142}{61221}Nikt nie powiedzia³,|¿e nie docenia trudu Jenny.
{61222}{61284}Jak ca³a robota to zrobienie|dziury w worku,
{61285}{61333}to sam bym sobie wyci¹³ lepsze.
{61334}{61396}A ty jak, Robert, widzisz coœ?
{61403}{61446}Nie za bardzo.
{61447}{61542}Jak nie ruszam g³ow¹,|to ciê widzê ca³kiem nieŸle.
{61543}{61646}Ale jak jadê, to mi worek lata naoko³o|i ni cholery nie widzê.
{61694}{61751}Chyba zepsu³em swój.
{61788}{61827}Wzi¹³ któryœ zapasowy worek?
{61828}{61902}Nie, nikt nie bra³ zapasowego worka.
{61913}{61950}Pytam tylko.
{61951}{61999}Musimy to nosiæ, jak jeŸdzimy?
{62000}{62033}Jasna cholera!
{62034}{62106}Bez tych worków zepsujemy nasz¹ akcjê.
{62107}{62154}Ale ja gówno widzê przez ten worek!
{62155}{62227}Oddychaæ nie mogê.|Nie bêdê w tym jeŸdzi³.
{62229}{62292}Pies was jeba³!|Wracam do domu.
{62293}{62426}¯ona ca³y dzieñ robi³a te 30 worków|dla was, niewdziêcznych sukinsynów.
{62427}{62506}A ci¹gle tylko s³yszê krytykê i krytykê!
{62532}{62604}Od teraz ani mnie, ani mojej|o nic nie proœcie!
{62636}{62664}S³uchajcie...
{62665}{62714}nie zapominajmy,|po co tu jesteœmy.
{62715}{62787}Mamy zabiæ czarnucha|za tamtym wzgórzem.
{62788}{62825}Musimy daæ im lekcjê.
{62826}{62862}Zg³upia³em ju¿.
{62863}{62914}Zak³adamy te worki, czy nie?
{62930}{63042}Myœlê, ¿e wszyscy uwa¿amy,|¿e worki by³y niez³ym pomys³em.
{63071}{63124}Ale nie wskazuj¹c nikogo palcem,
{63125}{63176}mog³y zostaæ zrobione lepiej.
{63194}{63231}Wiêc co wy na to...
{63233}{63283}¿adnych worków tym razem.
{63291}{63311}Ale nastêpnym
{63312}{63356}zrobimy takie, jakie trzeba
{63357}{63407}i jedziemy w pe³nej gali.
{63466}{63497}Chwila!
{63498}{63544}Nie powiedzia³em: œci¹gn¹æ worki.
{63545}{63594}Ale nikt nic nie widzi.
{63600}{63626}I co?
{63627}{63675}Dobrze by³oby widzieæ.
{63682}{63739}Niech was diabli!|To jest najazd!
{63743}{63817}Ja nie widzê, wy nie widzicie.|I co z tego?
{63821}{63877}Wa¿ne, ¿e jebane konie widz¹.
{63878}{63933}To jest w³aœnie najazd!
{64065}{64092}Tu jest.
{64093}{64141}Wyci¹gn¹æ tego czarnucha!
{64168}{64214}Wyci¹gn¹æ go!
{64215}{64257}Nie ma tu czarnucha!
{64258}{64272}Co?
{64274}{64293}Oszukali nas!
{64294}{64330}To gdzie oni s¹?
{64332}{64375}{y:i}Auf wiedersehen...
{64548}{64592}Idealnie.
{64634}{64677}Uciekaj¹.
{64786}{64846}Tchórze tak ju¿ maj¹.
{65175}{65219}Chcia³byœ?
{65444}{65468}Ucieka.
{65469}{65518}Mam go.
{65547}{65587}Tatusiek ucieka.
{65588}{65624}Mam go.
{65981}{66030}Dosta³em go.
{66163}{66199}Wrodzony talent.
{66445}{66542}Sk¹d wiesz, ¿e pierwsi w³aœciciele|Brunhildy byli Niemcami?
{66550}{66597}Brunhilda to niemieckie imiê.
{66598}{66664}Skoro j¹ tak nazwali,|to by œwiadczy³o, ¿e s¹ Niemcami.
{66666}{66738}Sporo dziewczyn z twoich stron|tak siê nazywa?
{66749}{66842}Brunhilda to imiê postaci z jednej
{66843}{66910}z najpopularniejszych niemieckich legend.
{66915}{66968}Jest opowieœæ o Brunhildzie?
{66969}{67018}Tak, jest.
{67151}{67185}Znasz j¹?
{67186}{67235}Ka¿dy Niemiec j¹ zna.
{67393}{67457}Chcia³byœ, ¿ebym ci j¹ opowiedzia³?
{67521}{67594}Brunhilda by³a ksiê¿niczk¹.
{67653}{67701}By³a córk¹ Wotana.
{67719}{67767}Boga wszystkich bogów.
{67786}{67852}Jej ojciec by³ na ni¹ wœciek³y.
{67853}{67903}Co zrobi³a?
{67923}{68020}Nie pamiêtam dok³adnie.|Chyba by³a mu jakoœ niepos³uszna.
{68024}{68098}Umieœci³ j¹ wiêc na szczycie góry.
{68104}{68153}Brunhilda by³a na górze?
{68154}{68245}To niemiecka legenda,|zawsze gdzieœ pojawi siê góra.
{68254}{68342}Umieœci³ smoki ziej¹ce ogniem,|by strzeg³y góry.
{68390}{68500}I otoczy³ j¹ pierœcieniem|piekielnego ognia.
{68546}{68633}I tam Brunhilda mia³a pozostaæ,
{68663}{68798}dopóki nie przyby³by bohater,|odwa¿ny dostatecznie, by j¹ uratowaæ.
{68833}{68876}I koleœ przyby³?
{68878}{68947}Tak, Django.|W istocie przyby³.
{68953}{69006}Koleœ zwany Zygfrydem.
{69018}{69068}Zygfryd j¹ uratowa³?
{69092}{69140}Dosyæ spektakularnie.
{69171}{69221}Wspi¹³ siê na górê,
{69242}{69290}poniewa¿ siê jej nie ba³.
{69291}{69336}Zg³adzi³ smoka,
{69337}{69390}poniewa¿ siê go nie ba³.
{69403}{69465}I wkroczy³ w pierœcieñ ognia,
{69515}{69577}poniewa¿ Brunhilda by³a tego warta.
{69668}{69722}Wiem, jak siê czu³.
{69737}{69821}Myœlê, ¿e zaczynam|zdawaæ sobie z tego sprawê.
{70018}{70068}S³uchaj, Django.
{70119}{70214}Nie w¹tpiê, ¿e któregoœ dnia|uratujesz swoj¹ ukochan¹.
{70241}{70339}Ale nie mogê ciê tak po prostu|puœciæ do Greenville.
{70351}{70454}Miasto aukcji niewolniczych nie|jest miejscem na odwiedziny.
{70467}{70565}Dla wolnego czy te¿ nie.|Jest po prostu zbyt niebezpieczne.
{70609}{70664}Pozwól, ¿e ci zadam pytanie.
{70829}{70893}Jak ci siê podoba biznes|£owców G³ów?
{70926}{70982}Zabijaæ bia³ych dla pieniêdzy?
{70999}{71043}Jak mo¿na tego nie lubiæ?
{71044}{71101}Muszê przyznaæ,|¿e tworzymy zgrany zespó³.
{71102}{71171}Myœla³em, ¿e by³eœ z³y na mnie|za zabicie Du¿ego Johna i Rogera.
{71173}{71229}W tamtej sytuacji by³eœ|nieco nadgorliwy.
{71230}{71280}Ale normalnie to dobre.
{71295}{71337}Chcia³byœ mi towarzyszyæ przez zimê?
{71338}{71405}Co masz na myœli mówi¹c "towarzyszy³"?
{71406}{71509}Pracowa³byœ ze mn¹ przez zimê,|a¿ do stopnienia œniegów.
{71533}{71607}Dam ci trzeci¹ czêœæ|moich nagród.
{71611}{71697}Zarobimy trochê tej zimy.|A gdy stopniej¹ œniegi,
{71711}{71772}zabiorê ciê osobiœcie do Greenville
{71786}{71860}i dowiemy siê,|gdzie wys³ali twoj¹ ¿onê.
{71958}{72032}Dlaczego obchodzi ciê,|co ze mn¹ bêdzie?
{72042}{72092}Dlaczego ciê obchodzi,|¿ebym znalaz³ ¿onê?
{72093}{72139}Tak szczerze...
{72168}{72232}nigdy nikomu wczeœniej|nie da³em wolnoœci.
{72233}{72326}Wiêc teraz czujê siê|jakoœ za ciebie odpowiedzialny.
{72343}{72415}A ponadto, gdy Niemiec spotyka|prawdziwego Zygfryda,
{72416}{72464}to jest to coœ.
{72493}{72545}Jako Niemiec jestem zobowi¹zany,
{72546}{72632}by pomóc ci w odnalezieniu|twojej ukochanej Brunhildy.
{72947}{73033}{y:i}Tak jak sosny otulaj¹ce krêt¹ drogê,
{73052}{73101}{y:i}mam swoje imiê.
{73116}{73165}{y:i}Mam swoje imiê.
{73217}{73304}{y:i}Jak œpiewaj¹cy ptak i rechocz¹ca ¿aba,
{73315}{73363}{y:i}mam swoje imiê.
{73383}{73432}{y:i}Mam swoje imiê.
{73482}{73574}{y:i}I noszê je podobnie, jak mój ojczulek.
{73583}{73699}{Y:i}Lecz ¿yjê marzeniami,|które on skrywa³ g³êboko.
{73751}{73800}{y:i}Wêdrujê wzd³u¿ szos¹.
{73811}{73860}{y:i}Toczê siê wzd³u¿ szosy.
{73874}{73963}{Y:i}Kroczê przed siebie,|wiêc ¿ycie mnie nie ominie.
{74077}{74169}{Y:i}Jak wiatr pó³nocny,|gwizdaj¹cy pod niebosk³onem,
{74180}{74229}{y:i}mam swoj¹ piosenkê.
{74246}{74294}{y:i}Mam swoj¹ piosenkê.
{74347}{74430}{y:i}Jak lelek nocny i dzieciêcy p³acz,
{74442}{74491}{y:i}mam swoj¹ piosenkê.
{74512}{74560}{y:i}Mam swoj¹ piosenkê.
{74609}{74700}{Y:i}Jest zawsze przy mnie|i œpiewam j¹ szczêœliwy.
{74714}{74776}{y:i}Gdy donik¹d mnie poniesie
{74777}{74827}{y:i}pójdê tam dumnie.
{74868}{74917}{y:i}Wêdrujê wzd³u¿ szos¹.
{74925}{74976}{y:i}Toczê siê wzd³u¿ szosy.
{75001}{75081}{Y:i}Kroczê przed siebie,|wiêc ¿ycie mnie nie ominie.
{75945}{76041}Co siê sta³o z tym, który chcia³|zabijaæ bia³ych dla pieniêdzy?
{76050}{76086}Jest z nim syn.
{76087}{76158}Dobrze. Bêdzie mia³ przy sobie|kogoœ ukochanego.
{76159}{76226}Mo¿e nawet wypowie ostatni¹ wolê.
{76268}{76373}To wiêcej, ni¿ otrzymuj¹ inni|i du¿o wiêcej, ni¿ na to zas³uguje.
{76563}{76611}Od³ó¿ strzelbê.
{76677}{76736}Nie przejmuj siê.|Nie jestem z³y na ciebie.
{76737}{76803}WeŸ list goñczy|Smitty'ego Bacalla.
{76885}{76935}Przeczytaj na g³os.
{76945}{77019}Potraktuj to jako dzisiejsz¹ lekcjê.
{77046}{77108}Poszukiwani ¿ywi lub martwy.
{77138}{77211}Smitty Bacall oraz jego gang.
{77279}{77362}Za morderstwo i napad na dyli¿ans.
{77442}{77485}Siedem, zero, zero...
{77486}{77535}Siedem tysiêcy.
{77561}{77609}Siedem tysiêcy dolarów
{77614}{77660}za Smitty'ego Bacalla,
{77661}{77735}tysi¹c piêæset za ka¿dego
{77736}{77820}z cz³onków jego gangu.
{77908}{78006}Znanymi cz³onkami jego gangu s¹,|jak nast¹puje:
{78032}{78080}Nastêpuje.
{78085}{78144}Dandy Michaels, Gerald Nash oraz...
{78191}{78239}Szalony Craig Koons.
{78268}{78331}Tym w³aœnie jest Smitty Bacall.
{78336}{78453}Gdyby chcia³ byæ farmerem w wieku 22 lat,|nigdy by tego nie wydrukowali.
{78461}{78527}Ale Smitty Bacall wola³ rabowaæ dyli¿ansy
{78528}{78614}i nie mia³ rozterek,|by w tym celu zabijaæ.
{78626}{78711}Chcesz uratowaæ swoj¹ ¿onê,|robi¹c to co ja?
{78732}{78773}To w³aœnie robiê.
{78774}{78857}Zabijam ludzi i sprzedajê|ich zw³oki za pieni¹dze.
{78859}{78932}Te zw³oki s¹ warte 7000 $.
{78966}{79040}Wiêc przestañ siê wykrêcaæ|i go zastrzel.
{79267}{79291}{y:i}Tato?
{79307}{79331}{y:i}Tato!
{79542}{79633}Masz tu list goñczy Smitty'ego,|zatrzymaj go.
{79635}{79658}Po co?
{79659}{79685}Na szczêœcie.
{79686}{79767}Zawsze trzymaj list goñczy|swojej pierwszej ofiary.
{80911}{80960}I to nazywam precyzj¹.
{82581}{82645}Doktorze, Django,|jak siê macie?
{82676}{82736}Kogo tam, cholera, wieziecie?
{82737}{82785}Gang Wilsona - Lowe'a.
{82793}{82865}A co to u diab³a za gang?
{82877}{82974}Z³y Chuck Wilson, jego podlec Billy Lowe|i ich trzech pomocników.
{83016}{83081}To zostaw ich tutaj,|nigdzie sobie nie pójd¹.
{83082}{83154}ChodŸcie do œrodka, zi¹b taki,|kawy siê napijecie.
{83179}{83255}Urodziny wczoraj mia³em,|ciasta trochê zosta³o.
{83257}{83307}Ca³kiem niez³ego.
{83517}{83600}Po bardzo srogiej i op³acalnej zimie.
{83602}{83692}Django i Dr Schultz zeszli z gór|i udali siê do...
{83837}{83880}MISSISIPI
{84756}{84831}Brunhilda Von Shaft.|Wiek 27.
{84835}{84908}"R" na prawym policzku.
{84921}{84976}Calvin J. Candie.
{84977}{85055}Ma jedn¹ z najwiêkszych|plantacji bawe³ny w Missisipi.
{85056}{85125}- "Candyland".|- Candyland?
{85126}{85206}- S³ysza³eœ o niej?|- Nie ma niewolnika, który o niej nie s³ysza³.
{85217}{85328}Widocznie tam jest twoja ¿ona,|a ten pod³y d¿entelmen jest jej panem.
{85351}{85405}Mam nadziejê,|¿e pracuje w domu, a nie w polu.
{85406}{85467}Ona nie jest do pracy w polu.
{85468}{85529}Jest ³adna.
{85534}{85587}Umia³a siê dobrze wyra¿aæ.
{85607}{85680}Jak ju¿ rozdarli jej plecy,
{85688}{85760}wypalili jej "r" uciekiniera na policzku.
{85768}{85821}Skurczybyki.
{85916}{85976}Ju¿ nie mog³a dalej|pracowaæ w domu.
{85978}{86028}Mieli z niej zrobiæ|dziewczynê do towarzystwa.
{86029}{86079}Co znaczy...?
{86101}{86170}Ale nie teraz, gdy jestem wolny...
{86171}{86214}Nie teraz, gdy mam gnata.
{86293}{86342}Spróbujemy j¹ zakupiæ?
{86397}{86433}Có¿...
{86473}{86613}Powiedzmy, ¿e cz³owiek chce kupiæ konia.
{86637}{86685}Potrzebuje konia.
{86708}{86820}Przychodzi do farmera, puka do drzwi|i mówi, ¿e chcesz kupiæ konia.
{86821}{86938}I co mówi farmer?|Farmer mówi nie.
{86961}{87041}To powiedzia³bym: jebaæ farmera.|I kradnê konia.
{87092}{87183}Dobrze, lecz wtedy zostajesz|koniokradem i ciê wieszaj¹.
{87195}{87248}Nie mówi¹c ju¿, ¿e koñ|wraca do w³aœciciela,
{87249}{87292}bo wci¹¿ do niego nale¿y.
{87293}{87365}Potrzebujemy jej i rachunek|jej sprzeda¿y.
{87379}{87454}To jak j¹ zdobêdziemy,|jeœli nie spróbujemy jej kupiæ?
{87471}{87575}- Mogê zaoferowaæ alternatywny plan?|- Œmia³o.
{87644}{87745}Cz³owiek idzie na farmê,|puka we frontowe drzwi,
{87756}{87887}i pyta nie o kupno konia,|lecz farmy.
{87902}{88027}I sk³ada ofertê tak niedorzeczn¹,|by zmusiæ farmera, by powiedzia³ "tak".
{88061}{88113}Z³o¿ymy ofertê kupna Candyland?
{88114}{88212}Jest za du¿e, ale farmerowi|nie chodzi tylko o farmê.
{88240}{88313}- Jak du¿o wiesz o walkach mandingo?|- Co?
{88323}{88450}- Potrafi³byœ przekonuj¹co udawaæ|eksperta od walk? - Po co?
{88481}{88567}Moj¹ postaci¹ bêdzie bogaty kupiec|z Dusseldorfu,
{88568}{88645}który chce tu w Greenville,|wejœæ w biznes walk mandingo,
{88646}{88747}a twoj¹ postaci¹ bêdzie ekspert od walk,|który mi w tym pomaga.
{88748}{88809}Nazywaj¹ takiego Jednooki Charlie.
{88858}{88934}- Bonjour.|- Bonjour, piêkna czarnulko.
{88946}{89030}Przyszliœmy spotkaæ siê panem|Calvinem Candie.
{89043}{89090}Proszê.
{89207}{89253}Mam graæ czarnego|handlarza niewolników?
{89254}{89340}Nie ma nic gorszego,|ni¿ czarny handlarz niewolników.
{89343}{89431}Czarny handlarz niewolników|jest ni¿ej ni¿ g³ówny czarny s³u¿¹cy.
{89453}{89510}I to jest, kolego, kurewsko nisko.
{89511}{89664}Wiêc tak go w³aœnie zagraj,|stañ siê czarnym handlarzem niewolników.
{89947}{90022}Doktorze Schultz,|dobrze znów pana widzieæ.
{90030}{90157}Panie Moguy, dziêkujê za pomoc|w zorganizowaniu tego spotkania.
{90163}{90215}Nonsens. To moja praca.
{90216}{90277}A to Jednooki Charlie,|o którym tyle s³ysza³em?
{90287}{90408}To jest Django, wyzwolony. A to jest|adwokat pana Candiego, Leonide Moguy.
{90415}{90457}Mów mi Leo.
{90459}{90528}Calvin jest w pokoju Juliusza Cezara.|Pójdziecie za mn¹?
{90548}{90602}Jak d³ugo jest pan powi¹zany|z panem Candie?
{90603}{90699}Z ojcem Calvina mieliœmy|po 11 lat jak poszliœmy do szko³y.
{90709}{90790}Ojciec ojca Calvina|umieœci³ mnie w szkole prawniczej.
{90791}{90858}Ktoœ by móg³ powiedzieæ,|¿e wychowano mnie na prawnika Calvina.
{90869}{90924}Ktoœ by móg³ powiedzieæ,|¿e jesteœ czarnuchem.
{90930}{90956}Co powiedzia³eœ?
{90957}{91027}Nic takiego, jest nieco pyskaty.
{91080}{91154}Czy powinienem coœ o nim wiedzieæ,|zanim go poznam?
{91155}{91214}Jest frankofilem.
{91215}{91255}Który cywilizowany cz³ek nie jest?
{91256}{91320}I preferuje monsieur Candie,|zamiast panie Candie.
{91322}{91370}Jakkolwiek sobie ¿yczy.
{91377}{91454}Proszê nie mówiæ do niego po francusku,|to go zawstydzi, nie zna francuskiego.
{91547}{91606}{y:i}Na górê, przewróæ go!
{91607}{91667}{y:i}I masz go.
{91711}{91778}Dlaczego chcesz wejœæ w biznes mandingo?
{91834}{91934}Nie zamierza pan zezwoliæ zastêpcy|na odpowiednie przedstawienie nas?
{91951}{92032}Nie przeci¹gaj i odpowiedz na pytanie.
{92091}{92218}Brutaln¹ prawdê? Jestem znudzony,|a to wydaje siê niez³¹ rozrywk¹.
{92367}{92469}To zapraszam, mamy tu niez³¹ walkê|w ramach tej rozrywki.
{92537}{92616}Potowarzyszysz mi do baru?
{92827}{92913}W domu nie nosi siê kapelusza,|nawet ja to wiem.
{93117}{93189}- Dr Schultz...|- Có¿ za rzadka...
{93190}{93237}- Walczyæ, czarnuchy!|- ...to dla mnie zaszczyt.
{93239}{93305}Zaszczyt pana poznaæ.|Proszê usi¹œæ.
{93307}{93381}Daj wolnemu Django,|cokolwiek bêdzie chcia³.
{93395}{93457}Dla mnie Sweet Tea Bourbon.
{93933}{93978}{y:i}Wykorzystaj swoj¹ masê!
{94007}{94058}{y:i}Jest du¿o wiêkszy i silniejszy.
{94067}{94140}Nie robi, co mu mówiê...|Do diab³a!
{94260}{94321}No dalej, to walka na œmieræ i ¿ycie!
{94354}{94436}Albo go walniesz, albo po tobie!
{94596}{94654}Dalej, Du¿y Fredzie...
{94674}{94724}Przewróæ go!
{94802}{94841}{y:i}Wykorzystaj si³ê!
{94853}{94881}Dalej, u¿yj si³y!
{95029}{95090}Masz go!|Spójrz na to.
{95188}{95247}{y:i}Rób, co ci mówi³em.
{95293}{95355}{y:i}Tak, jak ci mówi³em!
{95381}{95434}Oœlep go!
{96018}{96096}- Wykoñcz go.|- Nie, nie...
{96139}{96199}Dalej, wykoñcz go.
{96289}{96361}- Dlatego zw¹ go Du¿y Fred.|- Warty ka¿dego grosza.
{96368}{96411}{y:i}Arivederci, Luigi.
{96413}{96524}Wstawaj ch³opie, odpocznij trochê.|Œwietna robota, naprawdê da³eœ radê.
{97101}{97151}Tequila.
{97372}{97422}Jak siê zwiesz?
{97460}{97509}Django.
{97553}{97613}Mo¿esz przeliterowaæ?
{97642}{97734}D J A N G O
{97772}{97825}D jest nieme.
{97826}{97882}Wiem.
{98049}{98088}Moguy...
{98089}{98183}zajmiesz siê nowym ch³opakiem,|znajdziesz mu pokój z miêkkim ³ó¿kiem
{98184}{98238}i przyprowadzisz sztukê,|¿eby mu obci¹gnê³a.
{98239}{98339}- Rano b¹dŸ gotowy, jedziesz do Candyland.|- Tak, panie Candie.
{98342}{98385}A zanim pójdziesz, Roscoe...
{98386}{98439}daj Fredowi du¿e piwo.
{98531}{98641}- Smacznego, ch³opie, zas³u¿y³eœ.|- Tak, proszê pana.
{98863}{98949}- Jak siê nazywasz?|- Nazywa siê Django, wyzwolony.
{99031}{99079}Sk¹d go wytrzasn¹³eœ?
{99080}{99163}Z³¹czy³ nas przypadkowy zbieg okolicznoœci.
{99201}{99253}S³ysza³em o tobie.
{99265}{99405}Mówi³eœ wszystkim, ¿e moi zawodnicy|s¹ gówno warci. Zaciekawi³o mnie to.
{99434}{99508}Co czyni ciê takim ekspertem|od mandingo?
{99540}{99623}Mnie zaciekawi³o,|co ciebie czyni takim ciekawym.
{99683}{99754}- Coœ ty powiedzia³?|- Spokojnie, Butch.
{99756}{99830}Nie poczu³em siê obra¿ony.
{99838}{100004}{y:i}Monsieur Candie, wola³bym,|¿eby kierowa³ pan pytania wprost do mnie.
{100019}{100098}Nic pan nie ma do picia.|Mogê daæ coœ odœwie¿aj¹cego?
{100104}{100145}Poproszê piwo.
{100146}{100225}{y:i}Wunderbar, Roscoe,|piwo dla pana z brod¹.
{100226}{100307}Dla mnie Polinezyjski Po³awiacz Pere³,|tylko nie ¿a³uj rumu.
{100309}{100402}Doktorku, jestem wytrawnym|handlarzem niewolników.
{100410}{100521}Pan jest neofit¹. Po prostu|chcê wybadaæ, czy ten tu kowboj,
{100538}{100612}pana nie wykorzystuje.
{100613}{100656}Z ca³ym szacunkiem, monsieur Candie,
{100659}{100744}nie pytam pana o rady.
{100757}{100853}Odszuka³em pana, aby nabyæ walcz¹cego|murzyna powy¿ej wartoœci rynkowej.
{100868}{100941}Gdy zgodzi³ siê pan na spotkanie,|by³em przekonany,
{100942}{101018}¿e bêdziemy omawiaæ interesy.
{101067}{101125}Na razie nie omawiamy interesów.
{101127}{101176}Omawiamy moj¹ ciekawoœæ.
{101227}{101327}- Dziêkujê.|- Roscoe, Coco, idŸcie na zewn¹trz.
{101376}{101446}Sheba, ty zostañ.
{101458}{101529}Wiedzia³am, ¿e nie o mnie ci chodzi³o.
{101541}{101601}{y:i}Prost!
{101625}{101705}Wed³ug Moguy'ego,|jeœli robiê biznes z panem,
{101721}{101772}to robiê go z wami oboma.
{101773}{101826}On ocenia, a pan trzêsie kies¹?
{101838}{101939}Nie brzmia³o to zbyt pochlebnie,|ale tak mniej wiêcej to wygl¹da.
{101989}{102117}Bystrzaku! Moguy mówi³,|¿e ogl¹da³eœ mój afrykañski towar
{102118}{102167}i nie by³eœ pod wielkim wra¿eniem.
{102168}{102230}Nie za tak¹ cenê.
{102243}{102306}Wiêc chyba nie mamy|ju¿ o czym rozmawiaæ.
{102317}{102418}Bo jak chce pan ode mnie kupiæ mordobijców,|to w³aœnie takich mam do sprzedania.
{102425}{102495}On nie chce kupiæ czarnych,|których masz do sprzedania.
{102496}{102568}Chce takiego,|którego nie chcesz sprzedaæ.
{102579}{102675}Ale ja nie sprzedajê czarnuchów,|których nie chcê sprzedaæ.
{102738}{102811}Nie sprzeda pan najlepszego.
{102823}{102876}Nawet drugiego najlepszego.
{102885}{102966}Ale co do trzeciego najlepszego,|którego równie¿ pan nie chce sprzedaæ...
{102982}{103078}Gdybym z³o¿y³ panu sumê tak niedorzeczn¹,|¿e musia³by pan j¹ rozwa¿yæ...
{103089}{103150}Któ¿ wie, co siê wydarzy?
{103197}{103257}Jak¹ uwa¿a pan za niedorzeczn¹?
{103265}{103331}Za naprawdê utalentowanego osobnika,
{103332}{103381}{y:i}odpowiedniego czarnucha...
{103417}{103477}Ile byœ powiedzia³, Django?
{103478}{103569}12 000 dolarów.
{103706}{103790}Panowie, wzbudziliœcie moje zaciekawienie.
{103802}{103875}Teraz macie moje uwagê.
{104206}{104228}{y:i}Willie!
{104236}{104283}Zatrzymaj siê!
{104284}{104365}- Dzieñ dobry, panowie.|- Doktorze Schultz.
{104380}{104461}- Prawda, ¿e piêkny poranek?|- Najpiêkniejszy, jaki mo¿e byæ.
{104478}{104540}Mo¿e pojedzie pan z nami powozem?
{104557}{104640}- Bardzo dziêkujê.|- Konia niech pan tam przywi¹¿e.
{104835}{104895}{y:i}Django.
{104981}{105065}Zerwa³em stosunki z wieloma|moimi znajomymi frenologami,
{105068}{105153}poniewa¿ wierzê,|¿e jest poziom powy¿ej oœwiecenia,
{105154}{105196}powy¿ej uzdolnienia,
{105197}{105293}powy¿ej lojalnoœci,|do którego czarnuch mo¿e aspirowaæ.
{105300}{105388}Powiedzmy, ¿e jeden czarny|na dziesiêæ tysiêcy.
{105415}{105472}Wyj¹tkowy czarnuch.
{105473}{105547}S³oneczny dzieñ, co nie?
{105552}{105602}S³oñce w górze.
{105607}{105669}Œwieci nad nami wszystkimi.
{105780}{105829}{y:i}Proszê usi¹œæ, Doktorze.
{105830}{105904}- Co za zaszczyt.|- Przyjemnoœæ po naszej stronie.
{105957}{106089}...i wierzê, ¿e po jakimœ czasie,|wyj¹tkowe czarnuchy, jak ten tutaj,
{106096}{106149}stan¹ siê, jeœli nie powszechne,
{106151}{106199}to czêœciej spotykane.
{106257}{106362}Bystrzaku, ty jesteœ tym jednym|na dziesiêæ tysiêcy.
{106372}{106460}Masz trzymaæ szereg,|a nie nas doganiaæ, czarnuchu.
{106825}{106906}- Dotknij gnata, a po tobie.|- Spokój!
{106907}{106964}Wszystko widzia³em. Nic siê nie sta³o.
{106965}{107004}¯artuje pan? Ten czarnuch...
{107005}{107074}Powiedzia³em, ¿e nic siê nie sta³o!|Rêka z broni!
{107120}{107187}Ty te¿, Butch.
{107221}{107295}Nie zra¿ajcie do nas moich goœci.
{107326}{107432}- Hoot, wracaj na konia.|- Obojczyk mi z³ama³.
{107436}{107547}Mo¿e mu któryœ, na litoœæ bosk¹,|pomóc wejœæ na konia?
{107554}{107628}Szczêœciarz z ciebie, czarnuchu.
{107642}{107693}Lepiej s³uchaj swojego szefa, bia³asku.
{107695}{107791}- Szykuj siê na spacer w œwietle ksiê¿yca.|- WeŸmiesz mnie za rêkê?
{107951}{108009}Willie, wieŸ nas do domu.
{108079}{108127}Ruszaæ!
{109393}{109466}- Masz jakiœ problem z oczami?|- Nie, proszê pana.
{109470}{109559}- Mo¿e ci w nie obcasem przy³o¿yæ?|- Nie, proszê pana.
{109560}{109620}To trzymaj swoje ga³y z daleka ode mnie.
{109621}{109717}Spójrz na mnie jeszcze raz, œmierdzielu,|a dam ci powód, ¿eby mnie nie lubiæ.
{109719}{109769}¯wawo, smoluchu!
{109803}{109898}Musicie coœ wiedzieæ o mnie,|jestem gorszy od tych tu bia³ych.
{109920}{110001}Rêce przy dupie i nie wa¿cie siê|na mnie patrzeæ.
{110002}{110088}- Radzi sobie nieŸle.|- W istocie.
{110172}{110261}Mo¿emy siê zatrzymaæ,|bym móg³ pomówiæ z moim cz³owiekiem?
{110266}{110344}Mniemam, ¿e bêdê zachwycony|osobnikami z Candyland,
{110345}{110515}wiêc zanim to nast¹pi, chcia³bym ustaliæ|strategiê z moim powiernikiem.
{110599}{110648}Mogê siê dowiedzieæ, co pan wyrabia?
{110649}{110726}Jestem przekonany,|¿e Brunhilda jest w Candyland.
{110784}{110857}- Jest pan pewny?|- Nie nazywali jej imieniem,
{110858}{110938}ale to na pewno m³oda kobieta|z "r" mówi¹ca po niemiecku.
{110939}{111040}W tych warunkach nie m¹drze tak stwierdziæ,|ale myœlê, ¿e jest bezpieczna.
{111050}{111145}Nie daj siê ponieœæ ¿¹dzy zemsty.
{111174}{111245}- Zapomnia³eœ, po co tu jesteœmy?|- Tak pan myœli?
{111246}{111308}Przestañ zra¿aæ do siebie Candiego.
{111330}{111448}Chcesz, ¿eby maskarada wysz³a na jaw|albo co gorsza nas zabili?
{111450}{111558}Bo ja nie zamierzam|dokonaæ ¿ywota w Missisipi.
{111575}{111646}Nie zra¿am go, tylko intrygujê.
{111647}{111721}Wykorzystuj¹c tych biednych niewolników?
{111728}{111860}Mam w pamiêci cz³owieka, który kaza³|mi zabiæ innego przed jego synem.
{111863}{111923}Nawet okiem nie mrugn¹³.
{111934}{111988}Pamiêtasz to?
{112021}{112070}Oczywiœcie, ¿e tak.
{112071}{112202}Powiedzia³eœ wtedy "to mój œwiat,|a w nim nie da siê nie pobrudziæ".
{112234}{112320}Wiêc to w³aœnie robiê.|Brudzê siê.
{112397}{112514}Nieco to przekrêcasz, ale...
{112515}{112577}trafi³eœ w sedno.
{112644}{112704}Widzimy siê w Candyland.
{112859}{112909}Dobra, czarnuchy.
{112910}{112957}Do szeregu!
{112958}{113036}Ciebie te¿ siê to tyczy, Ksiê¿ycowy.
{114135}{114205}Niech mnie, d'Artagnan.
{114230}{114288}Co ci przysz³o do g³owy, ¿eby uciekaæ?
{114293}{114350}Nie mogê ju¿ d³u¿ej walczyæ,|{y:i}monsieur Candie.
{114351}{114456}Ale¿ mo¿esz.|Mo¿e nie wygrywaæ, ale walczyæ tak.
{114469}{114577}Panie Stonesipher, ucisz pan te psy,|w³asnych myœli nie s³yszê!
{114579}{114646}Marsha, spokój!
{114689}{114780}{y:i}Zabierzcie psy z dala od czarnucha.
{114994}{115104}- ZejdŸ ch³opcze z tego drzewa.|- Tak, proszê pana.
{115655}{115767}- Na jak d³ugo siê urwa³?|- Noc, dzieñ
{115773}{115882}- i pó³ kolejnej nocy.|- Jak daleko poza posiad³oœæ?
{115900}{116023}Jakieœ 22 mile.|Ca³kiem daleko, zw³aszcza, ¿e kuœtyka.
{116075}{116140}Panie Moguy, z kim d'Artagnan|mia³ w pi¹tek walczyæ?
{116142}{116210}Z jednym z nowych.
{116211}{116304}S¹dz¹c po jego stanie,|œlepy indianin by na niego nie postawi³.
{116308}{116381}Proszê, panie Candie,|nie mogê ju¿ d³u¿ej...
{116382}{116447}Nie p³aszcz mi siê tutaj.
{116449}{116529}Uderzasz w me czu³e serce.
{116591}{116670}Masz teraz k³opoty, synu.
{116732}{116804}Zap³aci³em za ciebie 500 $.
{116806}{116971}Jeœli tyle p³acê za czarnucha, to oczekujê,|¿e stoczy piêæ walk, zanim siê przekrêci.
{116979}{117070}Zrozum, ¿e prowadzê tu interes.
{117094}{117177}- Stoczy³eœ trzy walki.|- Ale wszystkie wygra³em.
{117178}{117295}To prawda. Ale w ostatniej by³eœ|na granicy zwyciêstwa i przegranej.
{117362}{117424}Tak, czy inaczej.
{117425}{117501}P³acê 500 $ i chcê piêæ cholernych walk.
{117519}{117574}Wiêc co z moimi pieniêdzmi?
{117625}{117682}Co z moimi piêcioma setkami?
{117686}{117768}Wyp³acisz mi odszkodowanie?
{117886}{117978}Nie wiesz, co znaczy "odszkodowanie"?
{118137}{118210}Ja panu wyp³acê.
{118274}{118329}Zrobi pan to?
{118336}{118394}Pewnie.
{118439}{118480}Zap³aci pan 500 $
{118482}{118586}za pó³œlepca, który siê nie nadaje,|by miot³¹ machaæ?
{118593}{118634}Wcale nie.
{118673}{118729}Jest zmêczony tymi gierkami.
{118750}{118776}Tak samo jak ja.
{118813}{118865}Ani grosza za niego nie zap³acimy.
{118866}{118939}Nic nam po nim, prawda Doktorze?
{118943}{119010}S³ysza³ go pan.
{119206}{119313}Musicie wybaczyæ panu Stonesipher|ten opad szczêki,
{119317}{119396}ale w ¿yciu nie widzia³|takiego czarnucha jak ty.
{119398}{119482}Mam racjê, panie Stonesipher?
{119501}{119557}Racja.
{119559}{119626}W takiej sytuacji
{119630}{119675}ja równie¿.
{119858}{119950}Jako, ¿e grosza byœ za niego nie da³,
{119997}{120094}chyba nie bêdziesz mia³ przeciwko,|bym potraktowa³ go tak jak chcê.
{120098}{120170}To twój czarnuch.
{120230}{120300}Panie Stonesipher...
{120304}{120425}Niech Marsha i jej suki wyœl¹|d'Artagnana do czarnych niebios.
{121407}{121457}Jak tak patrzê na twojego szefa,
{121458}{121526}to nie wiem jak zniesie krwawe walk.
{121551}{121677}Nie przywyk³ do widoku cz³owieka|rozrywanego przez psy.
{121681}{121729}Ale ty przywyk³eœ?
{121731}{121825}Bardziej przywyk³em do Ameryki,|ni¿ on.
{121829}{121909}A teraz monsieur Candie,
{121918}{121964}czekam.
{121966}{122048}Piêæ godzin ju¿ jedziemy,|¿eby zobaczyæ pana towar.
{122050}{122118}PrzejdŸmy wiêc do rzeczy.
{122122}{122184}Bo jeœli on mia³ byæ przyk³adem,
{122186}{122269}to nie jestem pod wra¿eniem.
{122275}{122333}Za mn¹.
{123654}{123725}Bank Missisipi.
{125394}{125444}Ustawiæ siê w szeregu!
{126910}{126951}Witajcie.|Stephen, mój ch³opcze.
{126953}{127011}Tak, tak, witajcie...
{127020}{127085}Co to za czarnuch na tej chabecie?
{127092}{127138}Stephen, gwoŸdzie zjad³eœ na œniadanie?
{127140}{127215}Czemu tak dra¿liwie?|Têskni³eœ za mn¹?
{127229}{127326}Têskni³em za panem,|jak œwinia za ³ajnem.
{127327}{127423}Jak dziecko têskni|za cyckiem mamy.
{127428}{127528}Brakowa³o mi pana,|jak kamienia w bucie.
{127595}{127682}Co ta za czarnuch na tym koniu?
{127694}{127754}Hej, Œnie¿ynko.
{127756}{127838}Jak chcesz znaæ imiê moje|albo mojego konia, spytaj mnie.
{127845}{127917}Kogo ty obesrañcu zwiesz œnie¿ynk¹?
{127919}{128001}Zrzucê ciê, obdartusie, z tej chabety|i nauczê szacunku...
{128003}{128066}Stephen, Stephen.
{128068}{128104}To tylko ¿arty.
{128106}{128178}- Django jest wolnym cz³owiekiem.|- Ten negatyw?
{128185}{128224}W³aœnie ten.
{128226}{128274}Pozwólcie, ¿e was przedstawiê.
{128276}{128368}Django, to Stephen,|taki sam pyskaty ga³gan jak ty.
{128372}{128452}Stephen, to jest Django.|Znienawidzicie siê nawzajem.
{128454}{128551}Co to za czarny gnojek,|¿e sam musisz mi go przedstawiaæ?
{128555}{128646}Django i jego kompan w szarym|Dr Schultz, s¹ naszymi klientami.
{128650}{128764}I naszymi goœæmi. Wiêc ty zgrzybia³y|³ajdaku winien im jesteœ goœcinnoœæ.
{128768}{128835}- Zrozumia³eœ?|- Tak, proszê pana...
{128837}{128891}Ale nie wiem, dlaczego mam|znosiæ uwagi tego czarnucha.
{128893}{128948}I nie musisz.|Wystarczy, ¿e zrozumiesz.
{128950}{129042}- Tak, proszê pana, zrozumia³em.|- Œwietnie.
{129044}{129133}Przenocuj¹ tutaj.|Przygotuj dwie sypialnie.
{129135}{129193}On zostaje w du¿ym domu?
{129195}{129250}Jest handlarzem niewolników.
{129252}{129289}W du¿ym domu?
{129291}{129373}- Masz z tym problem?|- Ani trochê.
{129377}{129488}Tylko, ¿e trza bêdzie spaliæ ³ó¿ko|i poœciel, jak ju¿ zabierze swoje dupsko.
{129489}{129540}To ju¿ mój problem.
{129542}{129600}Twój problem, to teraz zrobienie|dobrego wra¿enia.
{129602}{129725}I masz natychmiast ten problem|rozwi¹zaæ i przygotowaæ pokoje.
{129739}{129812}Tak, panie Calvinie.
{129823}{129871}IdŸ ju¿.
{129873}{129946}Nie wierzê,|¿e czarnuch bêdzie tu nocowa³.
{129948}{130012}Tatuœ pana w grobie siê teraz przewraca.
{130013}{130070}- Pyskuje jak najêty.|- I to coraz bardziej.
{130096}{130184}Gdzie jest moja piêkna siostra?!
{130202}{130264}Oto i jest!
{130292}{130379}Doktorze Schultz,|ten powabny po³udniowy klejnot,
{130381}{130413}to moja owdowia³a siostra.
{130415}{130500}Kochana, jesteœ jak balsam|na me strudzone oczy.
{130535}{130628}Przedstawiam panom|Larê Lee Candie-Fitzwilly.
{130639}{130722}Chester, Rodney, Tchórzliwy Charlie,|zagoñcie ich do zagrody.
{130723}{130760}Ruszaæ siê!
{130777}{130808}Wiecie, gdzie to jest!
{130809}{130844}Jak na smyczy!
{130870}{130958}Czarnuchy tu biegaj¹, a nie spaceruj¹!
{130960}{131031}{y:i}Monsieur Candie...
{131041}{131118}Co do tej czarnej dziewczyny,|o której mówiliœmy...
{131119}{131150}Czarnej dziewczyny?
{131151}{131234}Zdaje siê, ¿e mówi po niemiecku.
{131235}{131286}A tak, Hildie. Co z ni¹?
{131288}{131396}Czy przed pokazem mo¿e j¹ pan przys³aæ|do mojego pokoju?
{131400}{131458}Ty rozpustniku...
{131460}{131509}Pewnie, czemu nie.
{131511}{131569}Jak ju¿ poka¿esz pokoje,|idŸ po Hildie.
{131573}{131657}Czyst¹ i wypachnion¹ odstaw j¹|do pokoju Doktora.
{131659}{131761}W³aœciwie, to muszê o czymœ|panu powiedzieæ.
{131777}{131804}Co?
{131806}{131891}Hildie jest w Gor¹cej Skrzyni.
{131904}{131974}- Co ona tam robi?|- A jak pan myœli?
{131976}{132034}Zosta³a ukarana.
{132036}{132103}- Co zrobi³a?|- Znowu uciek³a.
{132105}{132171}To ilu ludzi uciek³o,|gdy mnie nie by³o?
{132172}{132206}Dwójka.
{132208}{132238}Kiedy uciek³a?
{132240}{132310}Ostatniej nocy.|Dzisiaj j¹ przyprowadzili.
{132312}{132384}Bardzo j¹ psy poszarpa³y?
{132386}{132468}Na szczêœcie dla niej|psy œciga³y d'Artagnana.
{132472}{132564}Bill i Cody za ni¹ ruszyli|i j¹ przyprowadzili.
{132568}{132679}Trochê jest potargana, ale sama to sobie|zrobi³a w tym cholernym buszu.
{132683}{132729}Jak d³ugo jest w skrzyni?
{132731}{132794}A jak pan myœli.|Ca³y przeklêty dzieñ.
{132796}{132869}I jeszcze posiedzi tam 10 dni.
{132873}{132940}- Wyci¹gn¹æ j¹.|- Wyci¹gn¹æ? Dlaczego?
{132942}{132990}Dlatego, ¿e tak powiedzia³em.
{132992}{133048}Dr Schultz jest moim goœciem.
{133050}{133149}Hildie jest moja, wiêc zgodnie z po³udniow¹|goœcinnoœci¹ udostêpniê mu j¹.
{133153}{133212}Ale ona uciek³a.
{133213}{133278}Po jak¹ cholerê trzymaæ|czarn¹ mówi¹c¹ po niemiecku,
{133280}{133350}skoro nie mo¿na jej wykorzystaæ,|gdy jest niemiecki goœæ.
{133352}{133449}Rozumiem, ¿e to niedogodne,|ale i tak j¹ wyci¹gnij.
{133453}{133516}Tak, proszê pana.
{133520}{133613}Laro Lee, dopilnujesz z Cor¹,|by odstawiæ Hildie przygotowan¹
{133614}{133674}do pokoju Doktora Schultza?
{133681}{133712}Oczywiœcie.
{133714}{133818}Wybaczcie mi panowie,|niewymownie jestem zmêczony podró¿¹.
{133822}{133893}Czas, by oczy odpoczê³y.
{134009}{134084}Nie stójcie tak, wyci¹gn¹æ j¹!
{134088}{134139}Cora! ChodŸ tu.
{134141}{134226}PrzyprowadŸ j¹,|wyczyœæ i zaprowadŸ do Doktora.
{134230}{134266}Jak tam siê pan nazywa³?
{134268}{134307}- Schultz.|- Schultz.
{134311}{134378}PrzyprowadŸ j¹. ¯wawo.
{135416}{135471}Nie!
{136253}{136356}Idziesz za mn¹,|czy wolisz spaæ w tej skrzyni?
{138636}{138680}Witajcie, panie.
{138682}{138782}Doktorze, mogê panu|przedstawiæ Brunhildê?
{138864}{138942}Hildie, to Doktor Schultz.
{138951}{139019}Mi³o ciê poznaæ.
{139034}{139107}Wiele dobrego o tobie s³ysza³em.
{139111}{139208}Có¿, niewiele czarnych|mówi po niemiecku.
{139241}{139391}Teraz widzê, ¿e ca³a pasja, której by³aœ przyczyn¹,|jest ca³kowicie usprawiedliwiona.
{139492}{139571}Doktor mówi po niemiecku.
{139586}{139668}Powiedziano mi,|¿e ty równie¿ nieŸle sobie radzisz.
{139672}{139751}Powiedz coœ po niemiecku.
{139770}{139877}Z przyjemnoœci¹ bêdê z panem|mówiæ po niemiecku.
{139922}{139970}Zadziwiaj¹ce.
{139974}{140063}{y:i}Fraulein, wejdŸ proszê do œrodka.
{140145}{140241}- Czy przynieœæ...?|- Piêknie dziêkujê.
{140341}{140435}- Mogê ci nalaæ szklankê wody?|- Tak.
{141000}{141077}Nie masz siê czego baæ.
{141116}{141188}Wybacz mi, proszê.
{141305}{141421}Uprzedzono mnie,|¿e d³ugi czas nie mówi³aœ po niemiecku.
{141518}{141595}Wiêc bêdê mówi³ powoli.
{141722}{141856}Mówiê po niemiecku, tylko w razie,|gdyby ludzie Candiego nas s³uchali.
{141989}{142020}{y:i}Pardon.
{142094}{142170}Jaka ty jesteœ piêkna.
{142194}{142254}Dziêkujê.
{142444}{142535}Ja i nasz wspólny przyjaciel
{142578}{142643}przezwyciê¿yliœmy mnóstwo k³opotów,
{142645}{142718}podró¿uj¹c wiele mil,
{142722}{142789}by ciê odnaleŸæ
{142839}{142899}i ocaliæ.
{142921}{142983}Pij, proszê.
{143053}{143150}Moim i naszego wspólnego|przyjaciela zamiarem
{143154}{143226}jest zabraæ ciê st¹d na zawsze.
{143228}{143298}Ja nie mam przyjació³.
{143302}{143363}Ale¿ masz.
{143391}{143422}Kogo?
{143424}{143507}Tego ci nie mogê powiedzieæ.
{143540}{143653}Nasz wspólny przyjaciel|ma zami³owanie do dramatyzmu.
{143693}{143773}Gdzie jest ten przyjaciel?
{143806}{143896}Stoi tu¿ za tamtymi drzwiami.
{144041}{144135}Obiecaj mi,|¿e nie bêdziesz krzyczeæ.
{144204}{144281}Powiedz, "obiecujê."
{144347}{144381}Obiecujê.
{144746}{144820}Czeœæ, ³obuziaku.
{145012}{145091}Ty z³otousty uwodzicielu.
{145117}{145153}Poœpiesz siê!
{145155}{145199}Nie, to ju¿ pili.
{145201}{145259}ZnajdŸ w piwnicy to,|które lubi pan Candie.
{145261}{145314}Rusz ten wielki ty³ek.
{145316}{145433}- Przecie¿ go lubisz.|- Tak jakbyœ wiedzia³a, co ja lubiê.
{145462}{145562}{y:i}Monsieur Candie,|sporo tu niez³ych okazów.
{145592}{145683}Ale najlepsze, póki co, by³y: Samson,
{145776}{145849}Goldie i Joe Eskimos.
{145860}{145933}W³aœciwie, to dlaczego tak siê nazywa?
{145937}{146002}Nikt nie wie, sk¹d siê bior¹|te ich przydomki.
{146004}{146126}Nazywa siê Joe i mo¿e powiedzia³|któregoœ dnia, ¿e mu zimno.
{146162}{146245}Niezale¿nie od tego,|Samson jest najlepszy.
{146249}{146288}Wszyscy to wiemy.
{146290}{146407}Pan go nigdy nie sprzeda|i dobrze to rozumiem. To mistrz.
{146417}{146494}Wszyscy trzej s¹ mistrzami.
{146498}{146609}Samson jest mistrzem.|Drudzy dwaj s¹ ca³kiem nieŸli.
{146621}{146688}- Calvin,co ten czarnuch...?|- W porz¹dku...
{146692}{146818}Musi pan wiedzieæ, ¿e chocia¿|jestem neofit¹ w walkach mandingo,
{146834}{146931}mam trochê rozeznania|w europejskich cyrkach objazdowych.
{146935}{146971}Czy¿by?
{146973}{147095}Od tego czasu mam spore pojêcie,|gdy dochodzi do prezentacji.
{147100}{147204}Potrzebujê czegoœ wiêcej,|ni¿ du¿ego czarnucha.
{147208}{147259}Musi byæ z polotem.
{147261}{147314}- Z czym?|- Panache...
{147318}{147374}Z iskr¹ gwiazdorstwa.
{147376}{147412}W³aœnie, gwiazdorstwa...
{147414}{147504}Chcê go wystawiæ|jako Czarnego Herkulesa.
{147508}{147558}Czarny Herkules, wymyœlnie.
{147560}{147631}Raczej Negrokules.
{147651}{147709}Tak jak powiedzia³em.
{147711}{147816}Zap³acê najwy¿sz¹ cenê|za odpowiedniego czarnucha.
{147860}{147959}Nie twierdzê, ¿e Joe Eskimos|jest lichym czarnym.
{147963}{148041}Ale czy to w³aœnie ten?
{148059}{148100}Doktorze Schultz...
{148102}{148200}musi pan wiedzieæ,|¿e nikt w tym biznesie
{148205}{148278}nie doceni gwiazdorstwa bardziej,|ni¿ Calvin J. Candie.
{148282}{148314}Nikt.
{148316}{148395}Lecz nie zapominajmy najwa¿niejszej|kwestii w walkach mandingo.
{148399}{148484}Najwa¿niejsze, by czarnuch wygrywa³ walki.
{148486}{148585}To powinno byæ pana|1,2,3,4 i 5-te zmartwienie.
{148589}{148693}Jak pan to bêdzie mia³,|mo¿e pan coœ ulepszaæ.
{148742}{148807}Innymi s³owy.|Najwa¿niejsze przede wszystkim.
{148809}{148877}Najwa¿niejsze...
{149066}{149114}Widzê, ¿e sobie przypadliœcie do gustu.
{149116}{149179}Jak najbardziej.
{149183}{149323}Nie wyobra¿a pan sobie, jak to jest latami|nie s³yszeæ swojego ojczystego jêzyka.
{149327}{149429}Ja sobie nie wyobra¿am|dwóch tygodni w Bostonie.
{149433}{149476}Dwóch tygodni w Bostonie!
{149478}{149539}Znakomite!
{149598}{149723}Wyraziæ nie potrafiê tej radoœci|mówienia znowu w swoim jêzyku.
{149730}{149840}A Hildie jest czaruj¹cym towarzyszem|w konwersacji.
{149845}{149954}Proszê uwa¿aæ, jeszcze panu zaszkodzi|nadmiar czarnej mi³oœci.
{149958}{150016}To potê¿na dawka uczuæ.
{150018}{150103}Jak czarny szpon chwyci pana|za p³aszcz.
{150107}{150163}Racja.
{150176}{150278}Doktorze, mo¿e pan j¹ raczyæ|wszelkimi niemieckimi pochlebstwami,
{150282}{150380}ale zdajê siê, ¿e ona upatrzy³a|sobie Django.
{150469}{150613}Zrozumia³e, ¿e jej spojrzenie przykuwa|szybuj¹cy orze³, a nie oskubana kura.
{150682}{150736}Doktorze, niech pan|nie bêdzie taki skromny.
{150740}{150836}Prawdziwy z pana europejski|d¿entelmen.
{150852}{150925}Znasz tego czarnucha, prawda?
{150929}{150968}Którego?
{150970}{151047}Wiesz, suko, o kim mówiê.
{151085}{151128}Ten przy stole?
{151130}{151167}Nie znam go.
{151171}{151234}- Nie znasz?|- Nie.
{151238}{151324}- Nie "co"?|- Nie, proszê pana.
{151425}{151499}Nie ok³ama³abyœ mnie?
{151564}{151631}Niech bêdzie.
{151660}{151730}Skoro tak mówisz.
{151869}{151978}Joe Eskimos to wartoœciowy czarnuch.|Bez w¹tpienia.
{151989}{152054}Ale za swoje pieni¹dze...
{152056}{152175}- Nie zap³aci³bym za niego 12 000$.|- Ile byœ za niego da³?
{152190}{152321}Jeœli mia³bym siê sk³aniaæ ku hojnoœci,|choæ sam nie wiem dlaczego...
{152329}{152380}9 000$.
{152382}{152435}Mo¿e.
{152439}{152568}Doktorze, pozwoli pan, ¿e przypomnê,|jak dosz³o do tych negocjacji.
{152569}{152636}To nie ja przyszed³em,|by sprzedaæ panu czarnego.
{152638}{152658}Dobrze mówi.
{152660}{152732}Pan do mnie dotar³, by go kupiæ.
{152734}{152816}Te 9 000, które rzuci³ bystrzacha|jest bliska wartoœci.
{152818}{152904}Ale za tak¹ sumê móg³bym go|sprzedaæ ka¿dego dzieñ.
{152905}{152944}Ka¿dego.
{152948}{152996}Ale jak pan powiedzia³ w Greenville...
{153000}{153056}Nie chcê go sprzedaæ.
{153060}{153195}Tylko pana niedorzeczne 12 000 $,|przekona³o mnie, ¿e tak siê mo¿e staæ.
{153425}{153541}No có¿ monsieur Candie,|posiada pan dar przekonywania.
{153633}{153730}Niech wiêc tak bêdzie.|Joe Eskimos za 12 000 $.
{153734}{153775}Wspaniale, Doktorze.
{153777}{153816}I to jest m¹dra decyzja.
{153820}{153905}Jednak¿e to ogromna suma pieniêdzy.
{153909}{153982}Tak jak pan,|ja równie¿ mam prawnika.
{153986}{154025}Pedantycznego pana Tuttle.
{154029}{154102}I bêdê potrzebowa³,|by sporz¹dzi³ on kontrakt,
{154106}{154193}zanim ze spokojem wymieniê|tak¹ sumê pieniêdzy za miêso.
{154197}{154306}Nie wspominaj¹c, ¿e Joe Eskimos|musi byæ przebadany przez lekarza.
{154310}{154346}Naturalnie.
{154348}{154443}Wiêc powiedzmy,|¿e powrócê za oko³o...
{154489}{154545}- Piêæ dni.|- Piêæ dni?
{154549}{154665}Z panem Tuttle, który z panem|Moguy'm dopnie formalnoœci.
{154724}{154778}Wybornie, Doktorze.
{154782}{154818}Wybornie.
{154820}{154866}Panowie...
{154868}{154950}Pozwólcie, ¿e wzniosê toast
{154976}{155064}za Joe Eskimosa, lub mo¿e raczej
{155074}{155130}Czarnego Herkulesa.
{155132}{155193}Za Czarnego Herkulesa.
{155197}{155245}Na zdrowie.
{155247}{155345}Racja, doktorze,|to imiê przyci¹ga uwagê.
{155364}{155416}Hildie...
{155420}{155481}Nalej mi.
{155528}{155644}Jak ci siê podoba s³u¿enie|do du¿ego sto³u w du¿ym domu?
{155652}{155732}Jak mounsieur Candie pyta,|to odpowiadasz.
{155736}{155799}Bardzo to lubiê, monsieur Candie.
{155803}{155905}Lepsze to, ni¿ le¿eæ w Gor¹cej Skrzyni|lub drapaæ ty³ek w buszu.
{155909}{155981}Choæ mo¿e nie a¿ tak przyjemne,|jak ogl¹danie mandingo,
{155983}{156027}- prawda cukiereczku?|- Oj tak, lubi ich.
{156029}{156094}Jak Simpsona, co?
{156098}{156135}{y:i}Monsieur Candie...
{156137}{156221}Doktor mo¿e byæ zainteresowany,|by zobaczyæ jej rozorane plecy,
{156225}{156303}jako, ¿e pewnie nie widzia³ wielu|czarnych stamt¹d, sk¹d pochodzi.
{156307}{156372}Doktorze, jak by³ pan z ni¹ na osobnoœci,
{156374}{156447}tylko rozmawialiœcie,|czy równie¿ œci¹ga³a ubranie?
{156451}{156494}Nie, my tylko rozmawialiœmy...
{156496}{156544}Wiêc nie widzia³ pan jej pleców?
{156546}{156571}Nie widzia³em...
{156573}{156646}Stephen ma racjê,|to mo¿e pana zainteresowaæ.
{156650}{156732}Hildie, œci¹gnij proszê sukienkê,|poka¿ Doktorowi plecy.
{156736}{156833}Calvin, dopiero co j¹ ³adnie ubra³am|i przygotowa³am.
{156837}{156943}Laro, Doktor Schultz jest z Dusseldorfu,|nie maj¹ tam czarnych.
{156947}{156983}Jest cz³owiekiem medycyny.
{156985}{157053}Jestem pewien, ¿e zafascynuje|go odpornoœæ czarnych na ból.
{157057}{157139}Bez w¹tpienia, Doktorze,|twarde s¹ te czarnuchy.
{157143}{157201}Hildie ma tu jakieœ 4 smagniêcia batem.
{157203}{157259}Laro Lee, ju¿ po jednym|odebra³o by ci zmys³y.
{157261}{157307}Spójrz, Doktorze, to jak malowid³o.
{157309}{157353}Calvin!
{157357}{157475}W³aœnie jemy, nikt nie chce|ogl¹daæ jej biczowanych pleców.
{157479}{157530}Ju¿ dobrze, dobrze....
{157534}{157608}Po obiedzie, Stephen.
{157623}{157707}W sam raz do brandy, panowie.
{157815}{157898}Cora, zabierz tê dziewczynê.
{157935}{157998}- Jak ona teraz wygl¹da...|- Tak, proszê pani.
{158002}{158048}Dlaczego jesteœ porozpinana?
{158050}{158139}Dopiero co ciê ubra³am, chodŸ tu.
{158268}{158357}Nie powinnaœ rzucaæ mu siê w oczy,|a podpadasz coraz bardziej.
{158361}{158434}Powiedzia³aœ, ¿e go nie znasz.
{158438}{158465}Co?
{158469}{158557}Powiedzia³aœ, ¿e go nie znasz...
{158632}{158676}Bo nie znam.
{158678}{158740}W³aœnie, ¿e znasz.
{158762}{158823}Panie Stephen...
{158827}{158859}Nie znam.
{158863}{158942}Dlaczego mnie ok³amujesz?
{158968}{159010}Nie k³amiê.
{159014}{159077}To dlaczego p³aczesz?
{159081}{159115}Przera¿a mnie pan.
{159119}{159180}Dlaczego ciê przera¿am?
{159184}{159261}Bo jest pan przera¿aj¹cy.
{159265}{159386}{Y:i}...rozmowa z Hildie po niemiecku|by³a duchowym ubogaceniem.
{159493}{159573}Nie ruszaj siê st¹d.
{159692}{159801}Oœwiadczy³ pan wczeœniej,|¿e zamierza siê po¿egnaæ z Hildie.
{159805}{159891}O tak, powiedzia³em coœ takiego.
{159918}{160037}W takim razie proszê mi pozwoliæ|zaproponowaæ jeszcze coœ.
{160066}{160091}Zamieniam siê w s³uch.
{160093}{160156}¯wawiej, psiakrew!
{160160}{160213}- Monsieur Candie...|- Stephen!
{160217}{160295}W³aœnie przerwa³eœ Doktorowi.
{160299}{160408}Przepraszam Doktorze,|mój s³uch ju¿ nie ten.
{160455}{160551}{y:i}Monsieur Candie,|mo¿emy zamieniæ s³owo w kuchni?
{160555}{160602}Czyli mam wstaæ ze swojego krzes³a?
{160606}{160652}Jeœli by pan móg³.
{160656}{160686}Po co?
{160690}{160726}Chodzi o deser.
{160730}{160777}Co z deserem?
{160781}{160843}Wola³bym omówiæ to na osobnoœci.
{160845}{160899}To ciasto bezowe.
{160901}{160961}Có¿ za melodramat|mia³by siê za nim kryæ?
{160965}{161062}Pan ma racjê bezwzglêdnie,|sam to za³atwiê.
{161071}{161110}Spotkajmy siê w bibliotece.
{161114}{161181}Nie rozumiem tylko,|dlaczego nie mo¿emy omówiæ kolacji,
{161183}{161237}jak siê póŸniej coœ pieprzy,|to wszystko na mnie.
{161241}{161309}Dobrze ju¿, przyjacielu...
{161313}{161364}Za moment pomówimy.
{161368}{161412}Tak, proszê pana.
{161416}{161455}Có¿...
{161459}{161484}panowie,
{161488}{161551}choæ bez w¹tpienia zdolnoœci|kucharskich im nie brakuje,
{161555}{161670}to od czasu do czasu odrobina|kontroli jest nieodzowna.
{161716}{161793}Wybaczcie mi na chwilê.
{161905}{161990}Mo¿ecie posprz¹taæ po kolacji.
{162051}{162087}Prêdzej, dziewczêta.
{162088}{162120}Doktorze Schultz...
{162121}{162202}mo¿e uraczy³by nas pan|opowieœciami o cyrku?
{162207}{162246}O cyrku?
{162421}{162464}Co to za sprawa?
{162591}{162701}Te skurwiele wcale nie chc¹|kupiæ zawodników.
{162716}{162766}Chc¹ tamt¹ dziewczynê.
{162804}{162873}Stephen, o czym ty bredzisz?
{162874}{162953}Dymaj¹ ciê w bambuko,|o tym mówiê.
{162960}{163039}Nie chc¹ ¿adnego miêœniaka,
{163058}{163101}tylko tê dziewczynê.
{163102}{163163}Jak¹ dziewczynê...?|Hildie?
{163164}{163224}Tak, Hildie.|Ona i Django...
{163226}{163277}czarnulki siê znaj¹.
{163301}{163340}W³aœnie kupi³ Joe Eskimosa.
{163341}{163374}Dosta³eœ pieni¹dze?
{163375}{163400}Jeszcze nie, ale pojad¹...
{163401}{163461}To go na razie nie kupili.|Póki co.
{163466}{163593}Ale w³aœnie mieli zamiar kupiæ tê,|po któr¹ przyjechali, gdy im przerwa³em.
{163605}{163667}Dziêkujê, Stephenie.|Ale¿ proszê, Calvinie.
{163804}{163857}Jak ty na to wpad³eœ?
{163876}{163935}Po cholerê tak by kombinowali,|by kupiæ czarn¹
{163936}{163997}z rozdartymi plecami,|nie wart¹ 3000$?
{163998}{164085}Dlatego, ¿e ten czarnuch Django|j¹ kocha.
{164099}{164142}To pewnie jego ¿ona.
{164144}{164236}Ale po co ten Niemiec|mia³by mu pomagaæ?
{164238}{164298}Tego ju¿ nie wiem.
{164355}{164401}Jeœli to jej w³aœnie chc¹...
{164411}{164511}po co ta ca³a gadka o mandingo?
{164519}{164590}Bo na 3000 $ nawet byœ nie splun¹³.
{164612}{164660}Ale 12 000?
{164679}{164737}Bardzo ciê im zjedna³o.
{164801}{164835}To prawda.
{164926}{164964}Jego ¿ona?
{165065}{165111}Gdyby to by³ w¹¿,
{165120}{165168}zmia¿d¿ylibyœmy go.
{165228}{165346}Tyle czasu posz³o siê jebaæ|przez tych
{165348}{165434}ob³udnych skurwysynów.
{165487}{165526}Skurwysyny!
{165528}{165648}... poza Nowym Orleanem, wiêc mia³am|trochê do czynienia z przedstawieniami.
{165677}{165715}Tu jesteœ.
{165717}{165804}Ju¿ myœla³am, ¿e gdzieœ uciekliœcie|z tym starym z³oœnikiem.
{165835}{165885}No to by by³o coœ.
{165892}{165915}Laro Lee,
{165916}{165957}przez okno zauwa¿y³em,|¿e Billy Crash
{165962}{166007}gada tam z jakimœ szemranym handlarzem,
{166010}{166065}który chce opchn¹æ grupkê dziewek.
{166067}{166144}Wyjdziesz na zewn¹trz|i rzucisz na nich okiem?
{166166}{166233}- Oczywiœcie, braciszku.|- Dziêkujê, kochana.
{166535}{166619}No tak, interesy nie œpi¹.
{166674}{166705}{y:i}A propos…
{166710}{166847}zanim pan wyszed³,|omawialiœmy mo¿liwoœæ zakupu Brunhildy.
{166849}{166904}Ach tak, zgadza siê.
{166921}{166978}Za chwilê do tego wrócimy.
{167364}{167425}Kim jest pana przyjaciel?
{167537}{167573}To Ben.
{167609}{167717}¯y³ tu przez d³ugi czas.
{167731}{167782}I mam na myœli kurewsko d³ugi czas.
{167815}{167861}Ten tutaj Ben
{167863}{167909}opiekowa³ siê moim tat¹
{167923}{167969}i tat¹ mojego taty,
{167978}{168036}a¿ pewnego dnia zabi³ sarnê,
{168105}{168153}któr¹ ja siê opiekowa³em.
{168206}{168300}Dorastaj¹cemu synowi w³aœciciela|wielkiej plantacji w Missisipi,
{168302}{168443}który jako bia³y styka³ siê|z tymi wszystkimi czarnymi twarzami.
{168487}{168606}Ca³e ¿ycie tu spêdzi³em,|w Candyland,
{168640}{168724}otoczony przez czarne twarze.
{168779}{168853}I widzia³em je dzieñ w dzieñ,|ca³y czas.
{168858}{168916}Zastanawia³o mnie tylko jedno.
{169007}{169059}Dlaczego nas nie zabij¹?
{169143}{169196}W³aœnie na tej tutaj werandzie,
{169201}{169261}trzy razy dziennie przez 50 lat,
{169263}{169374}stary Ben goli³ mojego|tatê ostr¹ brzytw¹.
{169390}{169513}A ja... na miejscu starego Bena|poder¿n¹³bym ojcu gard³o
{169515}{169604}i wcale by mi to nie zajê³o|50 lat.
{169661}{169709}Lecz on nigdy tego nie zrobi³.
{169738}{169774}Dlaczego?
{169803}{169833}Widzicie...
{169834}{169915}wiedza o frenologii,
{169916}{170040}jest kluczowa, by zrozumieæ ró¿nicê|miêdzy dwoma gatunkami.
{170083}{170141}W czaszce Afrykanów
{170177}{170236}fragment odpowiadaj¹cy za uleg³oœæ
{170237}{170364}jest wiêkszy, ni¿ u jakiegokolwiek|cz³owieka, czy podgatunku na Ziemi.
{170745}{170818}Jeœli siê przyjrzycie
{170819}{170899}temu fragmentowi czaszki,
{171018}{171117}zauwa¿ycie trzy wyodrêbnione wg³êbienia.
{171191}{171275}Tutaj, tutaj i tutaj.
{171285}{171311}Wiêc...
{171318}{171433}gdybym trzyma³ czaszkê Newtona,|albo Galileusza,
{171443}{171546}te trzy wg³êbienia by³yby umiejscowione|w czêœci mózgu odpowiedzialnej za
{171553}{171592}kreatywnoœæ.
{171601}{171661}Ale to jest czaszka starego Bena.
{171668}{171762}I w jego czaszce, obci¹¿onej genami,
{171776}{171877}te wg³êbienia s¹ w miejscu|odpowiedzialnym za...
{171901}{171951}s³u¿alczoœæ.
{171965}{172013}A teraz, bystrzaku...
{172023}{172083}Przyznajê, ¿e jesteœ ca³kiem rozgarniêty.
{172140}{172196}Ale gdybym chwyci³ ten m³otek
{172239}{172289}i wcisn¹³ ci w czaszkê,
{172318}{172380}mia³byœ te same trzy wg³êbienia,
{172392}{172445}w tym samym miejscu,
{172479}{172519}co stary Ben.
{172565}{172625}A teraz ³apska na stó³!
{172627}{172701}Jeœli je zabierzecie z tego sto³u|z ¿ó³wiej skorupy
{172702}{172778}pan Butch odpali obie lufy obrzyna!
{172807}{172885}Sporo k³amstw powiedziano|dzisiaj przy tym stole,
{172886}{172934}ale w to mo¿ecie uwierzyæ!
{172953}{172981}Panie Moguy,
{172982}{173073}by³by pan ³askaw zabraæ pistolety|z pasa tych panów?
{173188}{173223}Bardzo dziêkujê.
{173224}{173263}Doktorze.
{173356}{173397}Na czym skoñczyliœmy?
{173495}{173531}Frajer.
{173620}{173660}Ach tak...
{173665}{173780}chyba w³aœnie mia³ mi pan z³o¿yæ ofertê|w sprawie Brunhildy.
{173795}{173845}Mam racjê?
{173927}{173967}Dobrze wiêc.
{174013}{174061}Dawaæ tu Hildie!
{174126}{174174}Têdy, skarbie.
{174190}{174242}PosadŸ ty³ek na krzeœle!
{174243}{174278}Po³ó¿ rêce na stole.
{174279}{174337}I zamknij mordê.
{174416}{174521}Doktorze, w Greenville,|jak pan powiedzia³,
{174524}{174574}zap³aci pan za odpowiedniego czarnucha
{174576}{174658}niedorzeczn¹ sumê pieniêdzy.
{174668}{174737}Na co spyta³em,|jak¹ pan uwa¿a za niedorzeczn¹.
{174739}{174831}I pan odpowiedzia³|12 000 $.
{174857}{174948}Zwa¿aj¹c, ¿e przejechaliœcie|taki szmat drogi,
{174953}{174996}przez te wszystkie k³opoty
{174998}{175108}i tyle na³galiœcie,|by zakupiæ tê tu urocz¹ damê,
{175109}{175236}wydaje siê, ¿e to Brunhilda|jest tym w³aœnie odpowiednim czarnuchem.
{175267}{175329}I jeœli chcecie opuœciæ|Candyland z Brunhild¹,
{175356}{175485}cena za ni¹ to 12 000 $.
{175492}{175593}Widzê, ¿e preferuje pan styl|negocjacji "kupujesz, albo nie".
{175639}{175695}W rzeczy samej, doktorze.
{175696}{175842}Wed³ug prawa hrabstwa Chickasaw,|Brunhilda jest moj¹ w³asnoœci¹.
{175857}{175981}I mogê z moj¹ w³asnoœci¹ zrobiæ cokolwiek,|czego sobie za¿yczê.
{176008}{176166}Wiêc jeœli myœlicie, ¿e moja cena|za tego czarnucha jest za du¿a,
{176171}{176233}to moim ¿yczeniem jest
{176310}{176405}wzi¹æ ten m³otek i|zajebaæ j¹ na œmieræ!
{176406}{176456}Wprost przed wami!
{176466}{176569}Wtedy bêdziemy mogli zbadaæ|trzy wg³êbienia w czaszce Hildie.
{176576}{176605}Ju¿!
{176607}{176669}Jak bêdzie, doktorku?
{176686}{176707}Jak bêdzie?
{176708}{176794}Czy mogê zabraæ rêce,|by wydobyæ portfel?
{176837}{176874}Proszê.
{177197}{177235}Dwanaœcie.
{177322}{177360}Sprzedana!
{177372}{177509}Cz³owiekowi z nieprzeciêtn¹ brod¹|i jego przeciêtnemu czarnuchowi.
{177655}{177703}- Panie Moguy.|- Tak, Calvinie?
{177727}{177808}Proszê tym panom wypisaæ rachunek|na 12 000 $.
{177813}{177885}12 000 $.
{177928}{177986}Interesy z panami to przyjemnoœæ.
{177998}{178046}A teraz, panowie,
{178065}{178115}jeœli zechcecie do³¹czyæ|do mnie w salonie,
{178137}{178202}bêdziemy podawaæ ciasto bezowe.
{180309}{180354}Znakomicie, Calvinie.
{180415}{180484}Przepraszam, madame?
{180511}{180568}Mo¿e pani przestaæ graæ Beethovena?
{180570}{180619}Zabieraj rêce z tej harfy.
{180707}{180740}Doktorze.
{180741}{180802}- Nie mo¿e pan tam wchodziæ.|- Stephen...
{180803}{180851}- Nie ma po co tam wchodziæ.|- Niech idzie.
{180870}{180952}Jest trochê zdenerwowany.|To wszystko. Ja to za³atwiê.
{181568}{181604}Ciasta bezowego?
{181623}{181690}Dziêkujê, nie lubiê s³odkoœci.
{181918}{181978}Rozpamiêtuje pan,|jak pana wykiwa³em?
{181999}{182107}W³aœciwie to rozmyœla³em o tym biedaku,|którym nakarmi³ pan psy.
{182115}{182156}D'Artagnan.
{182182}{182251}I zastanawia mnie co Dumas,|by na to powiedzia³.
{182273}{182323}Proszê jaœniej.
{182383}{182477}Aleksander Dumas.|Napisa³ "Trzech Muszkieterów".
{182486}{182526}Oczywiœcie, Doktorze.
{182527}{182569}Wnoszê, ¿e pan go podziwia,
{182570}{182668}nazywaj¹c swego niewolnika|imieniem bohatera jego powieœci.
{182685}{182769}Gdyby Dumas by³ tam dzisiaj,
{182771}{182831}zastanawiam siê,|co by z tego uczyni³.
{182872}{182932}W¹tpi pan, ¿eby to zaaprobowa³.
{182963}{183086}Jego aprobata by³aby w najlepszym|razie bardzo w¹tpliwa.
{183143}{183203}¯abojad o miêkkim sercu?
{183234}{183294}Aleksander Dumas jest czarny.
{183380}{183424}Czy to dokumenty Brunhildy?
{183426}{183473}- Tak, to one.|- Mogê?
{183474}{183534}- Naturalnie.|- Dziêkujê.
{183582}{183707}Rachunek jej sprzeda¿y, historia w³asnoœci|oraz dokument jej wyzwolenia.
{183711}{183771}Czy móg³bym dostaæ pióro i atrament?
{183793}{183836}S¹ na tamtym stole.
{183838}{183872}Dziêkujê.
{184373}{184407}Dziêkujê.
{184491}{184541}Brunhildo Von Shaft
{184594}{184656}uwa¿aj siê za woln¹ kobietê.
{184939}{184989}Panie Candie,
{185030}{185114}normalnie rzek³bym auf wiedersehen.
{185131}{185231}Ale jako, ¿e auf wiedersehen|znaczy do zobaczenia,
{185248}{185334}i jako, ¿e nie ¿yczê sobie|znów pana ujrzeæ,
{185337}{185399}mówiê ¿egnaj.
{185502}{185550}ChodŸmy.
{185644}{185699}Jeszcze chwila, Doktorze!
{185735}{185771}Co?
{185869}{185929}Mamy tu na Po³udniu zwyczaj,
{185934}{186011}¿e gdy biznes dochodzi do skutku,|obie strony
{186025}{186075}œciskaj¹ sobie rêce.
{186085}{186135}W dobrej wierze.
{186138}{186200}- Nie jestem z Po³udnia.|- Lecz jest pan
{186212}{186260}w moim domu, Doktorze,
{186286}{186330}wiêc obawiam siê,|¿e muszê nalegaæ.
{186332}{186415}Nalegaæ? Na co?|By uœcisn¹æ pañsk¹ d³oñ?
{186416}{186506}Obawiam siê zatem,|¿e ja nalegam na coœ przeciwnego.
{186507}{186548}Wie pan, kim jest wed³ug mnie?
{186550}{186622}Nie interesuje mnie to.
{186665}{186718}Myœlê, ¿e jest pan marnym przegranym.
{186720}{186796}A pan beznadziejnym zwyciêzc¹.
{186797}{186842}Tak czy inaczej,
{186843}{186917}tu w hrabstwie Chickasaw|interes nie dochodzi do skutku,
{186919}{186992}dopóki obie strony|nie uœcisn¹ sobie d³oni.
{186998}{187082}Gówno znaczy, ¿e papiery s¹ podpisane,
{187092}{187166}dopóki nie uœciœnie pan mojej d³oni.
{187197}{187272}Jeœli nie uœcisnê pana d³oni,
{187274}{187336}wyrzuci pan 12 000 $?
{187341}{187392}Nie wydaje mi siê.
{187411}{187459}Panie Butch,
{187485}{187581}jeœli ona spróbuje wyjœæ, zanim ten|mi³oœnik czarnuchów nie uœciœnie mi d³oni,
{187598}{187651}odstrzel j¹.
{188168}{188245}Naprawdê chce pan,|¿ebym uœcisn¹³ panu d³oñ?
{188281}{188331}Nalegam.
{188355}{188408}Skoro pan nalega.
{188847}{188895}Calvin!
{188909}{188960}Calvin!
{189099}{189156}Przykro mi.|Nie mog³em siê oprzeæ.
{189463}{189514}Ten czarnuch zwariowa³!
{189523}{189588}Wszystkich rozniesie!
{189998}{190048}Jebany skurwiel!
{190288}{190398}Skurwysyn, co on odpierdala...
{190439}{190489}Co do k...
{190619}{190729}Kto mu, kurwa, da³ broñ?
{191525}{191597}No dawaj, czarnuchu,|rozwal mnie!
{193621}{193671}Wstrzymaæ ogieñ!
{193733}{193783}Wstrzymaæ ogieñ!
{193812}{193863}Przestaæ strzelaæ!
{194069}{194109}Django!
{194117}{194157}Co?
{194213}{194266}Mamy twoj¹ kobietê.
{194285}{194359}Billy Crash trzyma jej przy g³owie gnata.
{194371}{194419}Jak przestaniesz,
{194421}{194481}nie zrobi jej papki z mózgu.
{194486}{194532}I to nie jest groŸba!
{194553}{194601}To obietnica.
{194661}{194695}Mo¿esz siê poddaæ.
{194697}{194750}Rzuciæ broñ.
{194757}{194792}Nie zabijemy ciê.
{194793}{194828}Gówno prawda.
{194829}{194896}Szczerze, Django.|Przyrzekam na Boga.
{194930}{194973}Poddajesz siê?
{194975}{195030}Nic ci siê nie stanie.
{195076}{195129}I mam ci niby wierzyæ?
{195133}{195209}Gówno mnie obchodzi,|w co wierzysz albo nie!
{195210}{195282}Ja wierzê, ¿e jak w ci¹gu 10 sekund|siê nie poddasz,
{195285}{195334}wystrzelimy jej mózg.
{195335}{195385}W to uwierz!
{195481}{195517}Odpuœæ mnie.
{195519}{195535}Szeœæ!
{195536}{195570}Pozwól mi odejœæ!
{195572}{195589}Siedem!
{195591}{195626}– Za bardzo mi zale¿y.|– Django.
{195627}{195654}Osiem!
{195656}{195690}Kocham ciê.
{195692}{195720}Dziewiêæ!
{195721}{195762}– Stop!|– Nie...
{195819}{195869}Poddajê siê.
{195870}{195920}Nie s³yszê ciê, czarnuchu.
{195944}{195999}Powiedzia³em: poddajê siê.
{198881}{198931}Pobudka, czarnuchu.
{199061}{199123}Wiêc jesteœcie £owcami G³ów?
{199135}{199200}Od pocz¹tku mi nie pasowaliœcie.
{199226}{199336}ZnaleŸliœmy u was listy goñcze|i ksiêgê osobników przy siodle.
{199380}{199428}Muszê powiedzieæ,
{199435}{199513}¿e nigdy wczeœniej nie s³ysza³em|o czarnym £owcy G³ów.
{199514}{199603}Podoba³o ci siê zabijanie bia³ych|dla pieniêdzy?
{199615}{199689}Pewnie bardzo,|dopóki zabawa trwa³a.
{199912}{199966}Po¿egnaj siê z orzeszkami, czarnulku.
{199967}{199998}Na trzy.
{200010}{200041}Jeden.
{200051}{200082}Trzymam ciê.
{200092}{200125}Dwa.
{200128}{200178}Spokojnie, czarnuchu.
{200200}{200237}Kapitanie?
{200238}{200286}Pani Lara chce ciê widzieæ.
{200303}{200370}Ma jak¹œ sprawê|odnoœnie pogrzebu.
{200401}{200485}I zmieni³a zdanie co do|wykarczowania Django.
{200514}{200610}Odda go ludziom z LeQuint Dickey.
{200624}{200684}To nie spieszy³o siê jej,|¿eby mi powiedzieæ.
{200847}{200900}Co za rozczarowanie.
{201442}{201478}Ty i ja.
{201516}{201551}Tego
{201552}{201602}nie zabierzesz ze sob¹.
{201669}{201755}O twoim czarnym dupsku|przez ostanie kilka godzin
{201756}{201818}rozmawiali w du¿ym domu.
{201842}{201933}Biali chyba nigdy w ¿yciu|nie wpadaj¹ na genialne pomys³y.
{201935}{201993}Wszyscy tylko kombinowali,|jakby ciê tu zabiæ.
{201998}{202132}Wiêkszoœæ pomys³ów rozbija³a siê o to,|¿eby ci poucinaæ to i owo.
{202134}{202262}To mo¿e siê wydawaæ|dobrym pomys³em, ale...
{202302}{202437}jak utniesz murzynowi jaja,|wiêkszoœæ z nich siê wykrwawia w jakieœ
{202444}{202504}siedem minut.|Wiêkszoœæ.
{202549}{202597}Wiêcej ni¿ wiêkszoœæ.
{202602}{202650}Na to mówiê.
{202746}{202842}Czarnuch sprzedany do LeQuint Dickey|bêdzie mia³ gorzej.
{202868}{202934}A oni dalej swoje:|"wych³oszczmy go na œmieræ".
{202935}{203019}"Rzuæmy go do mandingo",|"psy nim nakarmimy".
{203024}{203146}Wiêc mówiê "co w tym takiego niezwyk³ego,|ca³y czas to robimy.
{203151}{203300}Niech mnie jasny szlag trafi, czarnuch|w LeQuint Dickey ma w cholerê gorzej."
{203326}{203489}I oto patrzcie, nie wiadomo sk¹d,|pani¹ Larê oœwieci³o, ¿ebyœmy
{203511}{203621}wys³ali twoje dupsko|LeQuint Dickey Mining Company.
{203657}{203760}A jako niewolnik|w LeQuint Dickey Mining Company,
{203777}{203863}od tego czasu,|a¿ w koñcu zdechniesz,
{203868}{203940}dzieñ w dzieñ, ka¿dego dnia,
{203947}{204007}bêdziesz œmiga³ m³otem dwurêcznym,
{204017}{204115}obracaj¹c du¿e ska³y w ma³e.
{204141}{204244}Jak ju¿ tam trafisz,|odbior¹ ci imiê,
{204249}{204321}dadz¹ numer i m³otek
{204323}{204379}i powiedz¹ "do roboty".
{204388}{204446}Jak zaczniesz pyskowaæ,|ur¿n¹ ci jêzyk,
{204448}{204503}dobrzy w tym s¹,|nie wykrwawisz siê.
{204510}{204570}Naprawdê znaj¹ siê na tym.
{204599}{204750}Bêdziesz tyra³ ca³y dzieñ,|dzieñ w dzieñ, a¿ siê wykoñczysz.
{204765}{204825}Potem stukn¹ ciê m³otem w ³eb
{204827}{204895}i wrzuc¹ twój ty³ek w murzyñski dó³.
{204896}{205024}I to bêdzie koniec|twojej historii, Django.
{205095}{205155}Droga do kopalni LeQuint Dickey.
{206198}{206249}Hej, bia³asie.
{206282}{206333}Powiedzia³em: hej, bia³asie.
{206335}{206404}Stul pysk. Nie masz nic do powiedzenia,|co chcia³bym us³yszeæ.
{206405}{206461}Co byœ powiedzia³,|¿eby zarobiæ 11 000 $?
{206462}{206495}Co mówisz?
{206496}{206576}Co byœ powiedzia³,|¿eby zarobiæ 11 000 $.
{206577}{206640}W³aœciwie to 11 500.
{206642}{206692}O czym ty pierdolisz?
{206695}{206751}Na tamtej plantacji Candyland
{206752}{206822}zosta³o 11 000 $,|po prostu sobie le¿y,
{206824}{206881}a wy przeszliœcie sobie obok.
{206882}{206933}Goñ siê, czarnulku.|Nie jesteœmy bandytami.
{206934}{206955}Tego nie powiedzia³em.
{206956}{207012}To jest fajne w tej fortunie,|¿e nie jest nielegalna.
{207013}{207051}Nie mo¿esz jej ukraœæ,
{207052}{207091}musisz na ni¹ zas³u¿yæ.
{207133}{207207}Jak chcesz coœ powiedzieæ, to mów.
{207208}{207289}11 500 czeka na ciebie w Candyland,
{207292}{207392}w ramach nagrody za Gang|Smitty'ego Bacalla.
{207395}{207464}- Kim, do kurwy, jest Smitty Bacall?|- To przywódca
{207467}{207533}gangu Bacalla,|morduj¹ i napadaj¹ na dyli¿anse.
{207534}{207643}Za niego jest 7000 $,|¿ywego lub martwego.
{207644}{207705}1500 za ka¿dego z jego kumpli.
{207706}{207754}Dandy Michaels,
{207757}{207794}Gerard Nash
{207795}{207858}i Szalony Craig Koons.
{207860}{207904}Wszyscy ci panowie
{207905}{207986}siedz¹ sobie w Candyland|i siê œmiej¹,
{207987}{208046}bo zabili i uda³o im siê zwiaæ.
{208047}{208091}Ale tak nie musi byæ,|ty i twoi kumple
{208092}{208178}mo¿ecie ich zdj¹æ|i zgarn¹æ nagrodê.
{208179}{208216}Mo¿esz powtórzyæ ten dowcip?
{208217}{208282}Sukinsyny...|zabili niewinnych ludzi,
{208284}{208326}w napadzie na dyli¿ans.
{208327}{208360}Niewinnych bia³ych.
{208361}{208469}Jak mi pozwolisz,|to z kieszeni wyci¹gnê nakaz na nich.
{208475}{208502}No to dawaj.
{208549}{208600}"Poszukiwani ¿ywi lub martwi.
{208601}{208667}Smitty Bacall i jego gang".
{208668}{208702}Przecie¿ jesteœ niewolnikiem.
{208704}{208748}Nie jestem niewolnikiem.
{208749}{208819}Czy mówiê jak niewolnik?
{208879}{208914}Jestem £owc¹ G³ów.
{208915}{208988}Wczoraj jako wolny cz³owiek
{208989}{209084}jeŸdzi³em w Candyland na koniu
{209085}{209133}z moim bia³ym, niemieckim wspólnikiem.
{209135}{209173}Dr Kingiem Schultzem.
{209174}{209250}Œcigaliœmy gang Bacalla od Teksasu
{209251}{209293}do hrabstwa Chickasaw.
{209294}{209373}W koñcu znaleŸliœmy|ich przy Candyland,
{209375}{209435}dopadliœmy ich,|sprawy trochê siê spieprzy³y,
{209438}{209487}mój wspólnik zgin¹³.
{209488}{209535}Calvin Candie zosta³ postrzelony.
{209536}{209591}Wszyscy zdecydowali,|¿eby mnie za to obwiniæ,
{209593}{209637}wiêc jestem tutaj.
{209639}{209730}Wiecie, ¿e nie ma mnie na liœcie,
{209732}{209797}i wiecie, ¿e nie powinno mnie tu byæ.
{209800}{209855}Ci kolesie wci¹¿ tam s¹,
{209857}{209892}wci¹¿ poszukiwani.
{209893}{210018}11 500 $ wci¹¿ jest do zgarniêcia, a oni siê|nie spodziewaj¹, ¿e wrócicie i zgarniecie ich.
{210020}{210070}To co to za interes?
{210071}{210137}Mówisz nam o nich,
{210138}{210187}puœcimy ciê i zwiewasz?
{210188}{210228}Wcale nie tak.
{210229}{210286}Dacie mi pistolet,
{210289}{210327}jednego konia
{210329}{210393}i 500 $ z tych 11 500 $,
{210394}{210441}a wska¿ê wam ich.
{210442}{210482}To prawdziwy list goñczy.
{210483}{210568}Ale to nie znaczy,|¿e ten postrzeleniec gada prawdê.
{210569}{210713}Tylko po co smoluch nosi³by|w kieszeni list goñczy.
{210828}{210900}Tamten czarnuch jeŸdzi³ wczoraj|konno w Candyland?
{211027}{211079}No dobra...
{211080}{211146}zapytam jeszcze raz.
{211147}{211235}I pamiêtajcie, ¿e nie lubiê k³amców.
{211236}{211387}Jest niewolnikiem z Candyland,|czy jeŸdzi³ wczoraj z bia³ym?
{211389}{211537}Tak, prowadzili nas z aukcji w Greenville,|a on jeŸdzi³ koniem z bia³ym.
{211538}{211611}Czy to by³
{211612}{211703}- niewolnik tego bia³ego?|- On nie by³ niewolnikiem.
{211706}{211757}Pewny jesteœ?
{211758}{211807}Pewny, jak cholera.
{211871}{211941}Co siê sta³o w Candyland?
{211943}{212012}Sporo strzelania, postrzelili pana.
{212013}{212073}- Kto go postrzeli³?|- Niemiec.
{212075}{212115}Czemu to zrobi³?
{212116}{212189}Czarny z Niemcem udawali handlarzy,|ale nimi nie byli.
{212190}{212254}To co to za jedni?
{212255}{212314}£owcy G³ów.
{212315}{212382}Roy, to mo¿e byæ coœ.
{212384}{212463}Dobra, smoluchu, umowa stoi.
{212516}{212570}Jeszcze jeden warunek.
{212571}{212625}Co znowu?
{212626}{212681}Jak tam ju¿ dojedziemy,
{212720}{212786}pomogê wam ich zabiæ.
{212787}{212834}Zabawny jesteœ, kolego.
{212835}{212894}Uwolnij go.
{212895}{212951}Ubi³eœ interes, czarnulku.
{212952}{213000}Ubi³eœ interes, brachu.
{213003}{213111}Jak na czarnego, jesteœ spoko.
{213324}{213385}Dostaniesz tego konia z tobo³kami.
{213386}{213433}Co w nich jest?
{213434}{213533}- Dynamit.|- Nie bêdê jeŸdzi³ koniem z dynamitem.
{213535}{213606}Chyba ciê rozumiem.|Frankie
{213607}{213703}weŸ laski z konia i wrzuæ je|do klatki z czarnuchami.
{213741}{213806}Macie tu dynamit, pobawcie siê.
{214070}{214143}Masz t¹ strzelbê na wózku?
{214144}{214169}Nom.
{214170}{214228}Daj mu swój pistolet i pas.
{214271}{214341}Tylko mi, kurwa, nie upuœæ.
{214343}{214393}W³aœnie ustawi³em celownik|i œmiga idealnie.
{214396}{214458}Dobrze wiedzieæ.
{216671}{216721}Dajcie mi ten dynamit.
{218865}{218912}- Jake!|- Taa?
{218913}{218997}Rusz siê zobaczyæ,|co temu psu odjeba³o.
{219107}{219155}D'Artagnan, skurwysyny!
{221308}{221358}{y:i}Auf wiedersehen.
{222778}{222826}To ja, skarbie.
{223990}{224086}{y:i}S³odkim niebawem
{224187}{224284}{y:i}spotkamy siê na tym piêknym wybrze¿u.
{224722}{224781}Cora, zaparzysz kawy?.
{224794}{224873}- Sheba, pomó¿ jej.|- Ju¿ idê.
{224926}{225096}{y:i}S³odkim niebawem...
{225125}{225217}Niebawem bêdziecie razem z Calvinem.
{225363}{225435}Tylko, ¿e trochê wczeœniej,|ni¿ s¹dziliœcie.
{225620}{225689}Billy Crash.|O czym my...?
{225708}{225746}A, tak.
{225767}{225815}Ostatnim razem,|jak ciê widzia³em,
{225816}{225872}trzyma³eœ ³apy na moim...
{226176}{226211}D-jango!
{226212}{226260}Ty czarny skurwysynu!
{226263}{226314}D jest nieme, kmiocie.
{226403}{226472}A teraz, wszystkim czarnym
{226473}{226575}proponujê pozostawiæ bia³ych.
{226577}{226629}Nie ty, Stephen.
{226638}{226712}Jesteœ tu, gdzie powinieneœ byæ.
{226733}{226784}Cora, zanim pójdziecie,
{226785}{226837}mo¿e powiecie pani Larze|"do widzenia"?
{226846}{226883}Co zrobiæ?
{226884}{226968}Powiedzcie pani Larze|"do widzenia".
{227004}{227053}Do widzenia, pani Laro.
{227146}{227195}A teraz zmykajcie.
{227629}{227661}Stephen.
{227662}{227735}Jak ci siê podobaj¹|moje nowe ³achy?
{227745}{227854}Wiesz, jak dot¹d nie s¹dzi³em,|¿e w burgundzie mi do twarzy.
{228090}{228166}Policzy³em szeœæ strza³ów, czarnuchu.
{228173}{228251}A ja dwa gnaty.
{228309}{228367}Powiedzia³eœ, ¿e przez 76 lat|na tej plantacji
{228368}{228426}widzia³eœ ró¿ne urazy u czarnych.
{228428}{228469}Ale zauwa¿y³em,
{228470}{228539}¿e o rzepce nie wspomnia³eœ.
{228549}{228590}Ty skurwielu.
{228591}{228683}76 lat Stephen. Jak myœlisz, ilu czarnych|przewinê³o siê w tym czasie?
{228684}{228722}7000?
{228723}{228764}8000?
{228777}{228836}9000? 9999?
{228887}{228980}Ka¿de s³owo, które wysz³o z ust Candiego,|by³o gównem,
{228981}{229027}ale w jednym mia³ racjê...
{229029}{229103}Ja jestem tym jednym|czarnym na 10 000.
{229276}{229350}Bo¿e, pozwól mi zabiæ|tego czarnucha.
{229356}{229425}Django, nie ujdzie ci to na sucho.
{229427}{229477}Zgarn¹ twoje czarne dupsko.
{229478}{229545}Od teraz bêdziesz na|listach goñczych,
{229546}{229606}£owcy G³ów bêd¹ ciê œcigaæ.
{229619}{229658}Mo¿esz uciec, czarnuchu,
{229660}{229712}ale oni ciê znajd¹.
{229715}{229764}A jak im siê to uda...
{229774}{229816}sam zobaczysz, co z tob¹ zrobi¹.
{229818}{229855}Nie tylko ciê zabij¹...
{229881}{229929}Masz przejebane.
{229930}{229985}To Candyland, czarnuchu.
{229988}{230049}Nie mo¿esz zniszczyæ Candyland.
{230051}{230084}Byliœmy tu
{230085}{230159}i zawsze bêdziemy!
{230670}{230727}Django!
{230731}{230795}Ty bezczelny skurw...
{230938}{231001}{y:i}Ten facet trzyma pos³uch w miasteczku,
{231029}{231072}{y:i}z niespokojnym gnatem.
{231109}{231189}{Y:i}Nie strzelaj dla zabawy, |by z niego zadrwiæ.
{231218}{231274}{y:i}Trzymaj bandziorów z daleka od niego.
{231307}{231354}{y:i}Trzymaj bandziorów z daleka od niego.
{231436}{231513}{y:i}Myœlisz pewnie, ¿e jest sennym kolesiem,
{231536}{231583}{y:i}nigdzie siê nie œpieszy.
{231621}{231670}-Hej, ³obuziaku.|{y:i}Ale pewny jestem,
{231671}{231728}-Hej, ³obuzie.|{y:i}¿e zmienisz szybko zdanie,
{231730}{231787}{y:i}gdy zobaczysz jak strzela.
{231820}{231871}{y:i}Gdy zobaczysz jak strzela.
{231923}{231993}{y:i}Jest najlepszy na Zachodzie,
{232019}{232081}{y:i}zawsze opanowany, perfekcyjny.
{232108}{232190}{y:i}Przy ¿yciu trzyma go Colt 45-ka.
{232381}{232429}Wiesz, jak ciê bêd¹ nazywaæ?
{232430}{232498}"Najszybszy gnat na Po³udniu".
{232673}{232722}Wynoœmy siê st¹d.
{232993}{233109}Napisy i teksty piosenek: hellcat|Korekta: Gall Anonim, maz445
{233111}{233234}Fragment Ksiêgi Rodzaju|na podstawie Biblii Tysi¹clecia.
{233394}{233544}www.Cinematix.TV - to Twoje internetowe|kino na ¿ywo. OdwiedŸ je koniecznie !!!
{233760}{233854}www.NapiProjekt.pl - nowa jakoœæ napisów.|Napisy zosta³y specjalnie dopasowane do Twojej wersji filmu.
