{40}{160}Downloaded From www.AllSubs.org
{1}{45}Ripped with SubRip 1.17 and Verified by CdinT|cdint@hotmail.com
{46}{55}I deliver perfection...|and don't brag about it! :D
{175}{210}So what do you think?
{216}{292}{y:i}Casa de Joey.
{298}{385}- I decorated it myself.|- Get out!
{391}{443}Wow, Joey, this is...
{449}{535}- Art.|- Art it is.
{541}{600}Check this out!|Is it a coffee table?
{606}{720}Is it a panther?|There's no need to decide.
{733}{782}Hey, nice pillow.
{788}{872}So tell me,|is this genuine Muppet skin?
{878}{953}Hey, excellent water, table thing.
{959}{1013}Thanks. I love this.|But you know what?
{1019}{1084}It makes me want to pee.
{1090}{1195}Yeah, me too.|I think that's the challenge.
{1203}{1306}How come Chandler didn't come?
{1318}{1368}It's because he had|a thing with the...
{1374}{1436}...with the thing.
{1461}{1535}Right. I got it.
{1536}{1641}So why don't you show us|the rest of your "casa"?
{1643}{1726}The best part! Come on.
{1896}{1948}Nice toilet.
{1954}{1989}No, no, no. Behind it.
{1995}{2058}- You have a phone in here?|- That's right.
{2064}{2094}I have a phone.
{2100}{2168}In here.
{2171}{2214}Joey, promise me something.
{2220}{2294}Never call me from that phone.
{2300}{2375}The One Where Eddie Moves In
{2381}{2443}English Subtitles by|GELULA & CO., INC.
{3720}{3785}Okay, here we go.
{3791}{3925}Sorry, they were all out of apple pie.|Someone just got the last piece.
{3931}{4000}Oh, my God!|You won't believe this!
{4006}{4090}I have just been discovered.
{4096}{4227}Wait a minute. I claimed you|in the name of France four years ago.
{4280}{4304}Anyway.
{4310}{4436}Don't freak out and say how|great this is until I'm done.
{4438}{4512}I just met this producer|of this teeny record company...
{4518}{4588}...who said that I have|a very fresh, offbeat sound...
{4594}{4708}...and she wants to do|a demo of "Smelly Cat".
{4720}{4808}Okay, I told you not to do that yet.
{4814}{4907}And she wants to do a video.
{4912}{4966}I'm not done yet, okay?
{4972}{5034}God!
{5034}{5165}If that goes well,|they may even want to make an album.
{5200}{5257}I'm done now.
{5316}{5397}If you care about me,|get the pie out of the man's hood.
{5403}{5506}- Get the what?|- There's a pie in the hood. Go!
{5642}{5661}What are you doing?
{5667}{5773}I'm sorry.|My pie was in your hood.
{5804}{5864}I have to get the coffee|out of that guy's pants...
{5870}{5966}...and I'll be back|in the hospital by 7.
{6074}{6165}Damn it, Ross!|Get your butt out of the bathroom!
{6171}{6243}Calm down. I'm blow-drying.
{6249}{6348}Blow-drying what?|You have no hair.
{6354}{6379}What's going on?
{6385}{6442}Your boyfriend has been|in there for an hour!
{6448}{6492}It's like I'm living with him again.
{6498}{6590}He's here when I go to sleep and|wake up and when I want to shower.
{6596}{6637}I feel like I'm 16 again.
{6643}{6723}Well, you're not 16.|You're both adults now.
{6729}{6801}Get out, you doofus!
{6830}{6942}Or, you know,|he's rubber and you're glue.
{6986}{7039}All yours.
{7045}{7146}I hope you cleaned your hair|out of the drain.
{7169}{7226}Shut up!
{7244}{7319}Cut it out!
{7411}{7502}I've never wanted you more.
{7721}{7826}So what do you say, boys?|Should I call him?
{7946}{7980}You know what they say:
{7986}{8065}Ask your slippers a question...
{8071}{8151}...you're going crazy.
{8319}{8395}I'm sorry I didn't make it|over there today.
{8401}{8432}That's okay.
{8438}{8493}You had a thing.
{8499}{8553}I hear the place looks great.
{8559}{8640}Forget about it.|I'm having a ball!
{8646}{8690}How's the apartment?
{8696}{8799}It's terrific.|I mean, it's a regular space...
{8800}{8863}...- fest!
{8883}{8920}Well, great.
{8926}{8965}{y:i}Yeah, I just...
{8971}{9054}...wanted to call and say hey.
{9060}{9109}Well, okay.
{9115}{9160}Was that the oven timer?
{9166}{9208}That's right, my friend.
{9214}{9248}{y:i}It's time for...
{9254}{9314}{y:i}... Baywatch!
{9378}{9438}Can you believe they gave|Stephanie skin cancer?
{9444}{9537}I can't believe|they made her lieutenant!
{9541}{9604}You're saying that because|you love Yasmine Bleeth.
{9610}{9718}How could anyone|not love Yasmine Bleeth?
{9731}{9790}Hey, they're running.
{9796}{9867}See, this is the|brilliance of the show.
{9873}{9951}I say always keep them running.
{9961}{10005}All the time running!
{10011}{10060}Run!
{10066}{10089}Run!
{10095}{10196}Run, Yasmine! Run like the wind!
{10208}{10253}But you wanted to live by yourself.
{10259}{10320}I did. I thought it'd be great.
{10326}{10403}I figured I'd have time alone|with my thoughts.
{10409}{10524}But it turns out I don't have|as many thoughts as you think.
{10530}{10600}Why don't you talk to Chandler|about moving back?
{10606}{10652}You really think he'd take me?
{10658}{10705}We had a good talk last night...
{10711}{10764}...but when I moved out,|I hurt him bad.
{10770}{10829}He would definitely want you back.
{10835}{10909}I'm telling you,|there's no way he's moving back.
{10915}{11009}But we had one of the greatest talks|we ever had last night.
{11015}{11044}I mean, it was...
{11050}{11125}It was like when we first|started living together.
{11131}{11199}I know you don't want|to hear this right now...
{11205}{11320}...but we've seen him|in his new place. And he's happy.
{11326}{11401}He's decorated.
{11410}{11495}Chandler, he has moved on, okay?|You have to, too.
{11501}{11590}You'll have to accept the fact|that you're just friends now.
{11596}{11640}You're not...
{11646}{11717}...roommates anymore.
{11723}{11808}Okay, Phoebe.|You ready to try one?
{11851}{11935}{y:i}Smelly cat, smelly cat
{11941}{12013}{y:i}What are they feeding you?
{12019}{12095}{y:i}Smelly, smelly, smelly|{y:i}Really bad smelling smelly cat
{12101}{12164}Whoa! Oh, my God!
{12211}{12291}I mean, like, who was that?
{12310}{12420}They're your backup singers.|Behind you, hon.
{12426}{12494}I thought they were just watching me.
{12500}{12554}Like at an aquarium, you know?
{12560}{12620}All right.
{12621}{12679}From the top.
{12685}{12761}{y:i}Smelly cat, smelly cat
{12767}{12874}{y:i}What are they feeding you?
{12965}{12992}Okay, sorry.
{12998}{13033}I'm just not getting...
{13039}{13085}...that everyone gets...
{13091}{13177}...how smelly|this cat actually is.
{13183}{13224}Maybe if we could talk about this...
{13230}{13352}...because I need to feel|that you really care about the cat.
{13376}{13395}We can talk.
{13401}{13485}It's just that this costs|$ 100 a minute to be in here.
{13491}{13588}So the cat stinks,|but you love it. Let's go.
{13594}{13675}No, there is no way|he was a velociraptor.
{13681}{13725}Look at the cranial ridge, okay?
{13731}{13847}If Dino was a velociraptor,|he'd have eaten the Flintstones.
{13886}{13913}Were you taking a nap?
{13919}{13960}I was.
{13966}{14062}Tony, can you hold on?|That's the other line.
{14068}{14140}Yeah, she's here,|but can she call you back?
{14146}{14180}Okay, thanks.
{14186}{14212}Call Joanna.
{14218}{14243}Did she leave a number?
{14249}{14332}Did you see me write one down?
{14338}{14426}I don't have her number, butt-munch.
{14438}{14491}She'll call back.|Don't be such a baby.
{14497}{14529}You're the baby.
{14535}{14600}- Get off my back.|- Get out of my face.
{14606}{14695}Wait, hold on, Tony. Hold on.
{14748}{14830}Yeah, she's right here.|Hold on.
{14836}{14894}Tony, can I call you back?
{14900}{14938}That's my sister's boyfriend.
{14944}{15016}Give me that.
{15056}{15186}Sweetie, before I forget, did I|leave my diaphragm at your place?
{15196}{15253}Hi, Mom.
{15786}{15829}So how's the palace?
{15835}{15925}It's funny you should mention that|because I was thinking...
{15931}{16011}What's with the boxes?
{16020}{16079}Actually, I have some news.
{16085}{16193}Is that Joey guy gonna pick up|his moose hat or should I toss it?
{16199}{16292}Why don't you ask him yourself?|This is my new roommate, Eddie.
{16298}{16324}Nice to meet you.
{16330}{16380}- Likewise.|- How you doing?
{16386}{16443}I'll take that.
{16449}{16526}It's what I came for.
{16529}{16580}This is new.|Where'd you two meet?
{16586}{16675}At the supermarket|in the ethnic food section.
{16681}{16762}I helped him pick out a chorizo.
{16790}{16915}We got to talking. He needed|a place, and I had a spare room.
{16921}{16953}Now it's a spare room?
{16959}{17025}Well, yeah.|In that it's not being used...
{17031}{17111}...and I have it to spare.
{17146}{17226}Well, I got what I came for.
{17288}{17345}I'll see you.
{17354}{17390}Hey, Joe.
{17396}{17493}When'd you start using|moose in your hair?
{17514}{17593}Is this guy great, or what?
{17599}{17669}Yeah, he is.
{17828}{17884}I can't believe he has|a new roommate. Who is he?
{17890}{17930}Eddie. He just met him.
{17936}{18056}It'll never last.|He's just a rebound roommate.
{18111}{18160}Check it out! Check it out!
{18166}{18249}It's "Smelly Cat", the video!
{18267}{18378}Now, I haven't seen it yet,|so if you don't like it...
{18384}{18482}...so what?|None of you ever made a video.
{18640}{18774}Get out of here, cat! You stink!
{18926}{18951}Smoking!
{18957}{18979}Look at me!
{18985}{19063}{y:i}Smelly cat, smelly cat
{19069}{19140}{y:i}What are they feeding you?
{19146}{19230}{y:i}Smelly cat, smelly cat
{19236}{19338}{y:i}It's not your fault
{19398}{19457}{y:i}Smelly, smelly, smelly|{y:i}Really bad smelling smelly cat
{19463}{19514}{y:i}It's not your fault
{19520}{19575}{y:i}Smelly cat, smelly cat
{19581}{19631}- Oh, my God!|- I know.
{19637}{19722}I sound amazing!
{19766}{19822}{y:i}They won't take you to the vet
{19828}{19884}{y:i}You're obviously not their favorite pet
{19890}{19948}{y:i}Smelly cat, smelly cat
{19954}{20036}{y:i}It's not your fault
{20080}{20134}I've never heard myself sing before.
{20140}{20205}I mean, except in my own head.
{20211}{20312}This is so cool!|Now I can hear what you hear!
{20321}{20392}Pretty different, huh?
{20398}{20500}I am sorry,|but I'm incredibly talented!
{20508}{20571}{y:i}Smelly cat, smelly cat
{20577}{20669}{y:i}It's not your fault
{20894}{20934}What's going on, man?
{20940}{20963}Eddie.
{20969}{21026}Morning.
{21035}{21127}I just came by to pick up my mail.
{21133}{21207}- Where's the mail?|- Over there on the table.
{21213}{21264}You don't keep it|on this table anymore?
{21270}{21345}Eddie likes it over there.
{21406}{21532}All right, here you go, my friend.|Eggs á la Eddie.
{21620}{21696}That's great.
{21716}{21740}What?
{21746}{21790}I thought you liked your eggs...
{21796}{21879}...with the bread with the hole|in the middle, á la me!
{21885}{21978}I do, but Eddie makes them this way.|They're pretty darn good.
{21984}{22024}Well, you guys...
{22030}{22081}...I'm out of here.
{22087}{22106}See you, pals.
{22112}{22171}See you.
{22220}{22304}- How are you two getting along?|- I couldn't be happier.
{22310}{22339}Great.
{22345}{22421}I'm happy for you.
{22469}{22520}All right, that's it!
{22526}{22653}He just comes in here,|Mr. Johnny New Eggs...
{22666}{22801}...with his moving the mail|and his "See you, pals".
{22831}{22860}And now there's no juice!
{22866}{22992}There's no juice for the people|who need the juice. I need the juice!
{22996}{23075}There's another carton there.
{23085}{23157}This isn't about juice anymore,|all right, man?
{23163}{23185}All right.
{23191}{23217}So what's it about?
{23223}{23267}Eggs!
{23273}{23337}Whose eggs do you like better,|his or mine?
{23343}{23415}- Well, I like both eggs equally.|- Oh, come on!
{23421}{23524}Nobody likes two eggs equally.|I wanna know which one you like better.
{23530}{23629}What's the difference?|Your eggs aren't here anymore.
{23634}{23693}You took your eggs and you left!
{23699}{23799}Did you expect me|to never find new eggs?
{23823}{23864}I wanna watch "Entertainment Tonight".
{23870}{23958}Tough. We're watching|{y:i}Predators of the Serengeti.
{23964}{23991}Would you guys stop!
{23997}{24044}It's my TV!
{24050}{24105}- Quit it!|- Bite me!
{24111}{24174}Monica keeps changing the channel.
{24180}{24250}That's great.|Why don't you tell Mommy on me?
{24256}{24325}Now I'm Mommy in this little play?
{24331}{24379}Look, I refuse to get sucked into...
{24385}{24462}...this weird little Geller|dimension thing, okay?
{24468}{24539}So I'm gonna go take|a nice long hot bubble bath...
{24545}{24651}...because you kids|are driving me crazy!
{24683}{24719}What do we do about this?
{24725}{24771}We could tape "Entertainment Tonight".
{24777}{24799}Not that!
{24805}{24849}This! Us!
{24855}{24914}Oh, my God, Ross, it's...|You're just...
{24920}{24980}Since you've been here,|you're driving me...
{24986}{25069}Mon, you've gone ultrasonic|again, all right?
{25075}{25147}I just can't stand you being here...
{25153}{25178}...all the time!
{25184}{25260}Why? Why can't you|stand me being here?
{25266}{25294}We're just having fun.
{25300}{25390}Fun? You think this is fun?
{25396}{25479}I thought we were fooling around,|like when we were kids.
{25485}{25566}I hated you when we were kids!
{25586}{25630}You hated me when we were kids?
{25636}{25659}I hated you.
{25665}{25723}I loved you in a you're-my-brother-|so-I-have-to way...
{25729}{25813}...but basically, I hated your guts.
{25813}{25841}Why did you hate me?
{25847}{25917}Because you were mean to me...
{25923}{26040}...and you teased me|and you always got your way.
{26048}{26121}That wasn't fun for you?
{26188}{26270}I can't believe you hated me.
{26281}{26361}But now I love you.
{26373}{26429}And not just because I have to.
{26435}{26496}Really?
{26520}{26623}You're just gonna have|to stop pissing me off.
{26703}{26743}I can do that.
{26749}{26836}Then I won't have to kill you.
{26875}{26958}So you wanna watch|"Entertainment Tonight"?
{26964}{27027}Thanks.
{27076}{27141}You know what?
{27144}{27266}If you really wanna watch|that Serengeti thing, we can.
{27463}{27549}Listen, you are not|going to believe this...
{27555}{27646}...but that is not me|singing on the video.
{27716}{27752}How did you find out?
{27758}{27862}The record company sent this paper|for me to sign saying it's okay...
{27868}{27975}...for someone else to sing for me.|That was my first clue.
{27981}{28005}What will you do?
{28011}{28072}I can't work with people|who would do this.
{28078}{28103}Sure.
{28109}{28169}I mean, this poor woman.
{28175}{28195}What woman?
{28201}{28230}The voice woman.
{28236}{28318}She has a great voice,|but she doesn't have a video.
{28324}{28374}Okay, Pheebs, but what about you?
{28380}{28464}I have a video. Pay attention.
{28508}{28583}This voice woman, she's so talented.
{28589}{28707}But according to the producer people,|she doesn't have the right look.
{28713}{28779}She's like one of those|animals at the pound...
{28785}{28844}...who nobody wants|because they're not pretty.
{28850}{28955}Or you know, like some old dog|who's kind of like stinky and...
{28961}{29045}Oh, my God! She's "smelly cat"!
{29093}{29177}That song has so many levels.
{29206}{29233}Hey, Eddie.
{29239}{29282}You wanna play some foosball?
{29288}{29389}No, thanks, man.|I'm not really into sports.
{29489}{29567}Yeah, okay. All right.
{29574}{29681}Doesn't matter.|Time for "Baywatch"!
{29689}{29757}You like that show?
{29783}{29846}You don't?
{29858}{29944}It's just pretty people|running around on the beach.
{29950}{30036}That's the brilliance of it.
{30056}{30125}The pretty people.
{30131}{30206}And the running.
{30215}{30309}I'm gonna go read in my room|for a little while.
{30315}{30386}Okay, man.
{30600}{30731}{y:i}I think of all the friends I've known
{30753}{30866}{y:i}But when I dial the telephone
{30902}{30991}{y:i}No one's home
{31148}{31297}{y:i}All by myself
{31303}{31342}{y:i}Don't wanna live
{31348}{31465}{y:i}All by myself
{31471}{31540}{y:i}Anymore
{31546}{31680}{y:i}All by myself
{31694}{31760}{y:i}Smelly cat, smelly cat
{31766}{31834}{y:i}What are they feeding you?|Everybody!
{31840}{31907}{y:i}Smelly cat, smelly cat
{31913}{31986}{y:i}It's not your fault
{31992}{32078}{y:i}They won't take you to the vet
{32143}{32220}{y:i}You're obviously not their favorite pet
{32226}{32292}{y:i}You may not be a bed of roses
{32298}{32388}{y:i}And you're no friend|{y:i}To those with noses
{32394}{32516}Ross, those are the only lines we have.|Back to the chorus!
{32556}{32956}Downloaded From www.AllSubs.org
